{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='envoyExtensionPolicy', url='', help='"EnvoyExtensionPolicy allows the user to configure various envoy extensibility options for the Gateway."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of EnvoyExtensionPolicy', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'gateway.envoyproxy.io/v1alpha1',
    kind: 'EnvoyExtensionPolicy',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"Spec defines the desired state of EnvoyExtensionPolicy."'),
  spec: {
    '#extProc':: d.obj(help='"ExtProc is an ordered list of external processing filters\\nthat should added to the envoy filter chain"'),
    extProc: {
      '#backendRefs':: d.obj(help='"BackendRefs defines the configuration of the external processing service"'),
      backendRefs: {
        '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
        withGroup(group): { group: group },
        '#withKind':: d.fn(help='"Kind is the Kubernetes resource kind of the referent. For example\\n\\"Service\\".\\n\\n\\nDefaults to \\"Service\\" when not specified.\\n\\n\\nExternalName services can refer to CNAME DNS records that may live\\noutside of the cluster and as such are difficult to reason about in\\nterms of conformance. They also may not be safe to forward to (see\\nCVE-2021-25740 for more information). Implementations SHOULD NOT\\nsupport ExternalName Services.\\n\\n\\nSupport: Core (Services with a type other than ExternalName)\\n\\n\\nSupport: Implementation-specific (Services with type ExternalName)"', args=[d.arg(name='kind', type=d.T.string)]),
        withKind(kind): { kind: kind },
        '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withNamespace':: d.fn(help="\"Namespace is the namespace of the backend. When unspecified, the local\\nnamespace is inferred.\\n\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { namespace: namespace },
        '#withPort':: d.fn(help='"Port specifies the destination port number to use for this resource.\\nPort is required when the referent is a Kubernetes Service. In this\\ncase, the port number is the service port number, not the target port.\\nFor other resources, destination port might be derived from the referent\\nresource or this field."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { port: port },
      },
      '#processingMode':: d.obj(help='"ProcessingMode defines how request and response body is processed\\nDefault: header and body are not sent to the external processor"'),
      processingMode: {
        '#request':: d.obj(help='"Defines processing mode for requests. If present, request headers are sent. Request body is processed according\\nto the specified mode."'),
        request: {
          '#withBody':: d.fn(help='"Defines body processing mode"', args=[d.arg(name='body', type=d.T.string)]),
          withBody(body): { processingMode+: { request+: { body: body } } },
        },
        '#response':: d.obj(help='"Defines processing mode for responses. If present, response headers are sent. Response body is processed according\\nto the specified mode."'),
        response: {
          '#withBody':: d.fn(help='"Defines body processing mode"', args=[d.arg(name='body', type=d.T.string)]),
          withBody(body): { processingMode+: { response+: { body: body } } },
        },
      },
      '#withBackendRefs':: d.fn(help='"BackendRefs defines the configuration of the external processing service"', args=[d.arg(name='backendRefs', type=d.T.array)]),
      withBackendRefs(backendRefs): { backendRefs: if std.isArray(v=backendRefs) then backendRefs else [backendRefs] },
      '#withBackendRefsMixin':: d.fn(help='"BackendRefs defines the configuration of the external processing service"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='backendRefs', type=d.T.array)]),
      withBackendRefsMixin(backendRefs): { backendRefs+: if std.isArray(v=backendRefs) then backendRefs else [backendRefs] },
      '#withFailOpen':: d.fn(help='"FailOpen defines if requests or responses that cannot be processed due to connectivity to the\\nexternal processor are terminated or passed-through.\\nDefault: false"', args=[d.arg(name='failOpen', type=d.T.boolean)]),
      withFailOpen(failOpen): { failOpen: failOpen },
      '#withMessageTimeout':: d.fn(help='"MessageTimeout is the timeout for a response to be returned from the external processor\\nDefault: 200ms"', args=[d.arg(name='messageTimeout', type=d.T.string)]),
      withMessageTimeout(messageTimeout): { messageTimeout: messageTimeout },
    },
    '#targetRef':: d.obj(help='"TargetRef is the name of the resource this policy is being attached to.\\nThis policy and the TargetRef MUST be in the same namespace for this\\nPolicy to have effect\\n\\n\\nDeprecated: use targetRefs/targetSelectors instead"'),
    targetRef: {
      '#withGroup':: d.fn(help='"Group is the group of the target resource."', args=[d.arg(name='group', type=d.T.string)]),
      withGroup(group): { spec+: { targetRef+: { group: group } } },
      '#withKind':: d.fn(help='"Kind is kind of the target resource."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { targetRef+: { kind: kind } } },
      '#withName':: d.fn(help='"Name is the name of the target resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { targetRef+: { name: name } } },
      '#withSectionName':: d.fn(help="\"SectionName is the name of a section within the target resource. When\\nunspecified, this targetRef targets the entire resource. In the following\\nresources, SectionName is interpreted as the following:\\n\\n\\n* Gateway: Listener name\\n* HTTPRoute: HTTPRouteRule name\\n* Service: Port name\\n\\n\\nIf a SectionName is specified, but does not exist on the targeted object,\\nthe Policy must fail to attach, and the policy implementation should record\\na `ResolvedRefs` or similar Condition in the Policy's status.\"", args=[d.arg(name='sectionName', type=d.T.string)]),
      withSectionName(sectionName): { spec+: { targetRef+: { sectionName: sectionName } } },
    },
    '#targetRefs':: d.obj(help='"TargetRefs are the names of the Gateway resources this policy\\nis being attached to."'),
    targetRefs: {
      '#withGroup':: d.fn(help='"Group is the group of the target resource."', args=[d.arg(name='group', type=d.T.string)]),
      withGroup(group): { group: group },
      '#withKind':: d.fn(help='"Kind is kind of the target resource."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { kind: kind },
      '#withName':: d.fn(help='"Name is the name of the target resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withSectionName':: d.fn(help="\"SectionName is the name of a section within the target resource. When\\nunspecified, this targetRef targets the entire resource. In the following\\nresources, SectionName is interpreted as the following:\\n\\n\\n* Gateway: Listener name\\n* HTTPRoute: HTTPRouteRule name\\n* Service: Port name\\n\\n\\nIf a SectionName is specified, but does not exist on the targeted object,\\nthe Policy must fail to attach, and the policy implementation should record\\na `ResolvedRefs` or similar Condition in the Policy's status.\"", args=[d.arg(name='sectionName', type=d.T.string)]),
      withSectionName(sectionName): { sectionName: sectionName },
    },
    '#targetSelectors':: d.obj(help='"TargetSelectors allow targeting resources for this policy based on labels"'),
    targetSelectors: {
      '#withGroup':: d.fn(help='"Group is the group that this selector targets. Defaults to gateway.networking.k8s.io"', args=[d.arg(name='group', type=d.T.string)]),
      withGroup(group): { group: group },
      '#withKind':: d.fn(help='"Kind is the resource kind that this selector targets."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { kind: kind },
      '#withMatchLabels':: d.fn(help='"MatchLabels are the set of label selectors for identifying the targeted resource"', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { matchLabels: matchLabels },
      '#withMatchLabelsMixin':: d.fn(help='"MatchLabels are the set of label selectors for identifying the targeted resource"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { matchLabels+: matchLabels },
    },
    '#wasm':: d.obj(help='"Wasm is a list of Wasm extensions to be loaded by the Gateway.\\nOrder matters, as the extensions will be loaded in the order they are\\ndefined in this list."'),
    wasm: {
      '#code':: d.obj(help='"Code is the Wasm code for the extension."'),
      code: {
        '#http':: d.obj(help='"HTTP is the HTTP URL containing the Wasm code.\\n\\n\\nNote that the HTTP server must be accessible from the Envoy proxy."'),
        http: {
          '#withSha256':: d.fn(help='"SHA256 checksum that will be used to verify the Wasm code.\\n\\n\\nIf not specified, Envoy Gateway will not verify the downloaded Wasm code.\\nkubebuilder:validation:Pattern=`^[a-f0-9]{64}$`"', args=[d.arg(name='sha256', type=d.T.string)]),
          withSha256(sha256): { code+: { http+: { sha256: sha256 } } },
          '#withUrl':: d.fn(help='"URL is the URL containing the Wasm code."', args=[d.arg(name='url', type=d.T.string)]),
          withUrl(url): { code+: { http+: { url: url } } },
        },
        '#image':: d.obj(help='"Image is the OCI image containing the Wasm code.\\n\\n\\nNote that the image must be accessible from the Envoy Gateway."'),
        image: {
          '#pullSecretRef':: d.obj(help='"PullSecretRef is a reference to the secret containing the credentials to pull the image.\\nOnly support Kubernetes Secret resource from the same namespace."'),
          pullSecretRef: {
            '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
            withGroup(group): { code+: { image+: { pullSecretRef+: { group: group } } } },
            '#withKind':: d.fn(help='"Kind is kind of the referent. For example \\"Secret\\"."', args=[d.arg(name='kind', type=d.T.string)]),
            withKind(kind): { code+: { image+: { pullSecretRef+: { kind: kind } } } },
            '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { code+: { image+: { pullSecretRef+: { name: name } } } },
            '#withNamespace':: d.fn(help="\"Namespace is the namespace of the referenced object. When unspecified, the local\\nnamespace is inferred.\\n\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { code+: { image+: { pullSecretRef+: { namespace: namespace } } } },
          },
          '#withSha256':: d.fn(help='"SHA256 checksum that will be used to verify the OCI image.\\n\\n\\nIt must match the digest of the OCI image.\\n\\n\\nIf not specified, Envoy Gateway will not verify the downloaded OCI image.\\nkubebuilder:validation:Pattern=`^[a-f0-9]{64}$`"', args=[d.arg(name='sha256', type=d.T.string)]),
          withSha256(sha256): { code+: { image+: { sha256: sha256 } } },
          '#withUrl':: d.fn(help='"URL is the URL of the OCI image.\\nURL can be in the format of `registry/image:tag` or `registry/image@sha256:digest`."', args=[d.arg(name='url', type=d.T.string)]),
          withUrl(url): { code+: { image+: { url: url } } },
        },
        '#withPullPolicy':: d.fn(help='"PullPolicy is the policy to use when pulling the Wasm module by either the HTTP or Image source.\\nThis field is only applicable when the SHA256 field is not set.\\n\\n\\nIf not specified, the default policy is IfNotPresent except for OCI images whose tag is latest.\\n\\n\\nNote: EG does not update the Wasm module every time an Envoy proxy requests\\nthe Wasm module even if the pull policy is set to Always.\\nIt only updates the Wasm module when the EnvoyExtension resource version changes."', args=[d.arg(name='pullPolicy', type=d.T.string)]),
        withPullPolicy(pullPolicy): { code+: { pullPolicy: pullPolicy } },
        '#withType':: d.fn(help='"Type is the type of the source of the Wasm code.\\nValid WasmCodeSourceType values are \\"HTTP\\" or \\"Image\\"."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { code+: { type: type } },
      },
      '#withConfig':: d.fn(help='"Config is the configuration for the Wasm extension.\\nThis configuration will be passed as a JSON string to the Wasm extension."', args=[d.arg(name='config', type=d.T.any)]),
      withConfig(config): { config: config },
      '#withFailOpen':: d.fn(help='"FailOpen is a switch used to control the behavior when a fatal error occurs\\nduring the initialization or the execution of the Wasm extension.\\nIf FailOpen is set to true, the system bypasses the Wasm extension and\\nallows the traffic to pass through. Otherwise, if it is set to false or\\nnot set (defaulting to false), the system blocks the traffic and returns\\nan HTTP 5xx error."', args=[d.arg(name='failOpen', type=d.T.boolean)]),
      withFailOpen(failOpen): { failOpen: failOpen },
      '#withName':: d.fn(help="\"Name is a unique name for this Wasm extension. It is used to identify the\\nWasm extension if multiple extensions are handled by the same vm_id and root_id.\\nIt's also used for logging/debugging.\\nIf not specified, EG will generate a unique name for the Wasm extension.\"", args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withRootID':: d.fn(help='"RootID is a unique ID for a set of extensions in a VM which will share a\\nRootContext and Contexts if applicable (e.g., an Wasm HttpFilter and an Wasm AccessLog).\\nIf left blank, all extensions with a blank root_id with the same vm_id will share Context(s).\\n\\n\\nNote: RootID must match the root_id parameter used to register the Context in the Wasm code."', args=[d.arg(name='rootID', type=d.T.string)]),
      withRootID(rootID): { rootID: rootID },
    },
    '#withExtProc':: d.fn(help='"ExtProc is an ordered list of external processing filters\\nthat should added to the envoy filter chain"', args=[d.arg(name='extProc', type=d.T.array)]),
    withExtProc(extProc): { spec+: { extProc: if std.isArray(v=extProc) then extProc else [extProc] } },
    '#withExtProcMixin':: d.fn(help='"ExtProc is an ordered list of external processing filters\\nthat should added to the envoy filter chain"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='extProc', type=d.T.array)]),
    withExtProcMixin(extProc): { spec+: { extProc+: if std.isArray(v=extProc) then extProc else [extProc] } },
    '#withTargetRefs':: d.fn(help='"TargetRefs are the names of the Gateway resources this policy\\nis being attached to."', args=[d.arg(name='targetRefs', type=d.T.array)]),
    withTargetRefs(targetRefs): { spec+: { targetRefs: if std.isArray(v=targetRefs) then targetRefs else [targetRefs] } },
    '#withTargetRefsMixin':: d.fn(help='"TargetRefs are the names of the Gateway resources this policy\\nis being attached to."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetRefs', type=d.T.array)]),
    withTargetRefsMixin(targetRefs): { spec+: { targetRefs+: if std.isArray(v=targetRefs) then targetRefs else [targetRefs] } },
    '#withTargetSelectors':: d.fn(help='"TargetSelectors allow targeting resources for this policy based on labels"', args=[d.arg(name='targetSelectors', type=d.T.array)]),
    withTargetSelectors(targetSelectors): { spec+: { targetSelectors: if std.isArray(v=targetSelectors) then targetSelectors else [targetSelectors] } },
    '#withTargetSelectorsMixin':: d.fn(help='"TargetSelectors allow targeting resources for this policy based on labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetSelectors', type=d.T.array)]),
    withTargetSelectorsMixin(targetSelectors): { spec+: { targetSelectors+: if std.isArray(v=targetSelectors) then targetSelectors else [targetSelectors] } },
    '#withWasm':: d.fn(help='"Wasm is a list of Wasm extensions to be loaded by the Gateway.\\nOrder matters, as the extensions will be loaded in the order they are\\ndefined in this list."', args=[d.arg(name='wasm', type=d.T.array)]),
    withWasm(wasm): { spec+: { wasm: if std.isArray(v=wasm) then wasm else [wasm] } },
    '#withWasmMixin':: d.fn(help='"Wasm is a list of Wasm extensions to be loaded by the Gateway.\\nOrder matters, as the extensions will be loaded in the order they are\\ndefined in this list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='wasm', type=d.T.array)]),
    withWasmMixin(wasm): { spec+: { wasm+: if std.isArray(v=wasm) then wasm else [wasm] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
