{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='securityPolicy', url='', help='"SecurityPolicy allows the user to configure various security settings for a\\nGateway."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of SecurityPolicy', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'gateway.envoyproxy.io/v1alpha1',
    kind: 'SecurityPolicy',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"Spec defines the desired state of SecurityPolicy."'),
  spec: {
    '#authorization':: d.obj(help='"Authorization defines the authorization configuration."'),
    authorization: {
      '#rules':: d.obj(help='"Rules defines a list of authorization rules.\\nThese rules are evaluated in order, the first matching rule will be applied,\\nand the rest will be skipped.\\n\\n\\nFor example, if there are two rules: the first rule allows the request\\nand the second rule denies it, when a request matches both rules, it will be allowed."'),
      rules: {
        '#principal':: d.obj(help='"Principal specifies the client identity of a request."'),
        principal: {
          '#withClientCIDRs':: d.fn(help='"ClientCIDRs are the IP CIDR ranges of the client.\\nValid examples are \\"192.168.1.0/24\\" or \\"2001:db8::/64\\"\\n\\n\\nThe client IP is inferred from the X-Forwarded-For header, a custom header,\\nor the proxy protocol.\\nYou can use the `ClientIPDetection` or the `EnableProxyProtocol` field in\\nthe `ClientTrafficPolicy` to configure how the client IP is detected."', args=[d.arg(name='clientCIDRs', type=d.T.array)]),
          withClientCIDRs(clientCIDRs): { principal+: { clientCIDRs: if std.isArray(v=clientCIDRs) then clientCIDRs else [clientCIDRs] } },
          '#withClientCIDRsMixin':: d.fn(help='"ClientCIDRs are the IP CIDR ranges of the client.\\nValid examples are \\"192.168.1.0/24\\" or \\"2001:db8::/64\\"\\n\\n\\nThe client IP is inferred from the X-Forwarded-For header, a custom header,\\nor the proxy protocol.\\nYou can use the `ClientIPDetection` or the `EnableProxyProtocol` field in\\nthe `ClientTrafficPolicy` to configure how the client IP is detected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='clientCIDRs', type=d.T.array)]),
          withClientCIDRsMixin(clientCIDRs): { principal+: { clientCIDRs+: if std.isArray(v=clientCIDRs) then clientCIDRs else [clientCIDRs] } },
        },
        '#withAction':: d.fn(help='"Action defines the action to be taken if the rule matches."', args=[d.arg(name='action', type=d.T.string)]),
        withAction(action): { action: action },
        '#withName':: d.fn(help='"Name is a user-friendly name for the rule.\\nIf not specified, Envoy Gateway will generate a unique name for the rule.n"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
      },
      '#withDefaultAction':: d.fn(help='"DefaultAction defines the default action to be taken if no rules match.\\nIf not specified, the default action is Deny."', args=[d.arg(name='defaultAction', type=d.T.string)]),
      withDefaultAction(defaultAction): { spec+: { authorization+: { defaultAction: defaultAction } } },
      '#withRules':: d.fn(help='"Rules defines a list of authorization rules.\\nThese rules are evaluated in order, the first matching rule will be applied,\\nand the rest will be skipped.\\n\\n\\nFor example, if there are two rules: the first rule allows the request\\nand the second rule denies it, when a request matches both rules, it will be allowed."', args=[d.arg(name='rules', type=d.T.array)]),
      withRules(rules): { spec+: { authorization+: { rules: if std.isArray(v=rules) then rules else [rules] } } },
      '#withRulesMixin':: d.fn(help='"Rules defines a list of authorization rules.\\nThese rules are evaluated in order, the first matching rule will be applied,\\nand the rest will be skipped.\\n\\n\\nFor example, if there are two rules: the first rule allows the request\\nand the second rule denies it, when a request matches both rules, it will be allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='rules', type=d.T.array)]),
      withRulesMixin(rules): { spec+: { authorization+: { rules+: if std.isArray(v=rules) then rules else [rules] } } },
    },
    '#basicAuth':: d.obj(help='"BasicAuth defines the configuration for the HTTP Basic Authentication."'),
    basicAuth: {
      '#users':: d.obj(help='"The Kubernetes secret which contains the username-password pairs in\\nhtpasswd format, used to verify user credentials in the \\"Authorization\\"\\nheader.\\n\\n\\nThis is an Opaque secret. The username-password pairs should be stored in\\nthe key \\".htpasswd\\". As the key name indicates, the value needs to be the\\nhtpasswd format, for example: \\"user1:{SHA}hashed_user1_password\\".\\nRight now, only SHA hash algorithm is supported.\\nReference to https://httpd.apache.org/docs/2.4/programs/htpasswd.html\\nfor more details.\\n\\n\\nNote: The secret must be in the same namespace as the SecurityPolicy."'),
      users: {
        '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
        withGroup(group): { spec+: { basicAuth+: { users+: { group: group } } } },
        '#withKind':: d.fn(help='"Kind is kind of the referent. For example \\"Secret\\"."', args=[d.arg(name='kind', type=d.T.string)]),
        withKind(kind): { spec+: { basicAuth+: { users+: { kind: kind } } } },
        '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { basicAuth+: { users+: { name: name } } } },
        '#withNamespace':: d.fn(help="\"Namespace is the namespace of the referenced object. When unspecified, the local\\nnamespace is inferred.\\n\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { basicAuth+: { users+: { namespace: namespace } } } },
      },
    },
    '#cors':: d.obj(help='"CORS defines the configuration for Cross-Origin Resource Sharing (CORS)."'),
    cors: {
      '#withAllowCredentials':: d.fn(help='"AllowCredentials indicates whether a request can include user credentials\\nlike cookies, authentication headers, or TLS client certificates."', args=[d.arg(name='allowCredentials', type=d.T.boolean)]),
      withAllowCredentials(allowCredentials): { spec+: { cors+: { allowCredentials: allowCredentials } } },
      '#withAllowHeaders':: d.fn(help='"AllowHeaders defines the headers that are allowed to be sent with requests."', args=[d.arg(name='allowHeaders', type=d.T.array)]),
      withAllowHeaders(allowHeaders): { spec+: { cors+: { allowHeaders: if std.isArray(v=allowHeaders) then allowHeaders else [allowHeaders] } } },
      '#withAllowHeadersMixin':: d.fn(help='"AllowHeaders defines the headers that are allowed to be sent with requests."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowHeaders', type=d.T.array)]),
      withAllowHeadersMixin(allowHeaders): { spec+: { cors+: { allowHeaders+: if std.isArray(v=allowHeaders) then allowHeaders else [allowHeaders] } } },
      '#withAllowMethods':: d.fn(help='"AllowMethods defines the methods that are allowed to make requests."', args=[d.arg(name='allowMethods', type=d.T.array)]),
      withAllowMethods(allowMethods): { spec+: { cors+: { allowMethods: if std.isArray(v=allowMethods) then allowMethods else [allowMethods] } } },
      '#withAllowMethodsMixin':: d.fn(help='"AllowMethods defines the methods that are allowed to make requests."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowMethods', type=d.T.array)]),
      withAllowMethodsMixin(allowMethods): { spec+: { cors+: { allowMethods+: if std.isArray(v=allowMethods) then allowMethods else [allowMethods] } } },
      '#withAllowOrigins':: d.fn(help='"AllowOrigins defines the origins that are allowed to make requests."', args=[d.arg(name='allowOrigins', type=d.T.array)]),
      withAllowOrigins(allowOrigins): { spec+: { cors+: { allowOrigins: if std.isArray(v=allowOrigins) then allowOrigins else [allowOrigins] } } },
      '#withAllowOriginsMixin':: d.fn(help='"AllowOrigins defines the origins that are allowed to make requests."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowOrigins', type=d.T.array)]),
      withAllowOriginsMixin(allowOrigins): { spec+: { cors+: { allowOrigins+: if std.isArray(v=allowOrigins) then allowOrigins else [allowOrigins] } } },
      '#withExposeHeaders':: d.fn(help='"ExposeHeaders defines the headers that can be exposed in the responses."', args=[d.arg(name='exposeHeaders', type=d.T.array)]),
      withExposeHeaders(exposeHeaders): { spec+: { cors+: { exposeHeaders: if std.isArray(v=exposeHeaders) then exposeHeaders else [exposeHeaders] } } },
      '#withExposeHeadersMixin':: d.fn(help='"ExposeHeaders defines the headers that can be exposed in the responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='exposeHeaders', type=d.T.array)]),
      withExposeHeadersMixin(exposeHeaders): { spec+: { cors+: { exposeHeaders+: if std.isArray(v=exposeHeaders) then exposeHeaders else [exposeHeaders] } } },
      '#withMaxAge':: d.fn(help='"MaxAge defines how long the results of a preflight request can be cached."', args=[d.arg(name='maxAge', type=d.T.string)]),
      withMaxAge(maxAge): { spec+: { cors+: { maxAge: maxAge } } },
    },
    '#extAuth':: d.obj(help='"ExtAuth defines the configuration for External Authorization."'),
    extAuth: {
      '#grpc':: d.obj(help='"GRPC defines the gRPC External Authorization service.\\nEither GRPCService or HTTPService must be specified,\\nand only one of them can be provided."'),
      grpc: {
        '#backendRef':: d.obj(help='"BackendRef references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent.\\nOnly Service kind is supported for now.\\n\\n\\nDeprecated: Use BackendRefs instead."'),
        backendRef: {
          '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
          withGroup(group): { spec+: { extAuth+: { grpc+: { backendRef+: { group: group } } } } },
          '#withKind':: d.fn(help='"Kind is the Kubernetes resource kind of the referent. For example\\n\\"Service\\".\\n\\n\\nDefaults to \\"Service\\" when not specified.\\n\\n\\nExternalName services can refer to CNAME DNS records that may live\\noutside of the cluster and as such are difficult to reason about in\\nterms of conformance. They also may not be safe to forward to (see\\nCVE-2021-25740 for more information). Implementations SHOULD NOT\\nsupport ExternalName Services.\\n\\n\\nSupport: Core (Services with a type other than ExternalName)\\n\\n\\nSupport: Implementation-specific (Services with type ExternalName)"', args=[d.arg(name='kind', type=d.T.string)]),
          withKind(kind): { spec+: { extAuth+: { grpc+: { backendRef+: { kind: kind } } } } },
          '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { extAuth+: { grpc+: { backendRef+: { name: name } } } } },
          '#withNamespace':: d.fn(help="\"Namespace is the namespace of the backend. When unspecified, the local\\nnamespace is inferred.\\n\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { extAuth+: { grpc+: { backendRef+: { namespace: namespace } } } } },
          '#withPort':: d.fn(help='"Port specifies the destination port number to use for this resource.\\nPort is required when the referent is a Kubernetes Service. In this\\ncase, the port number is the service port number, not the target port.\\nFor other resources, destination port might be derived from the referent\\nresource or this field."', args=[d.arg(name='port', type=d.T.integer)]),
          withPort(port): { spec+: { extAuth+: { grpc+: { backendRef+: { port: port } } } } },
        },
        '#backendRefs':: d.obj(help='"BackendRefs references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent.\\nOnly Service kind is supported for now."'),
        backendRefs: {
          '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
          withGroup(group): { group: group },
          '#withKind':: d.fn(help='"Kind is the Kubernetes resource kind of the referent. For example\\n\\"Service\\".\\n\\n\\nDefaults to \\"Service\\" when not specified.\\n\\n\\nExternalName services can refer to CNAME DNS records that may live\\noutside of the cluster and as such are difficult to reason about in\\nterms of conformance. They also may not be safe to forward to (see\\nCVE-2021-25740 for more information). Implementations SHOULD NOT\\nsupport ExternalName Services.\\n\\n\\nSupport: Core (Services with a type other than ExternalName)\\n\\n\\nSupport: Implementation-specific (Services with type ExternalName)"', args=[d.arg(name='kind', type=d.T.string)]),
          withKind(kind): { kind: kind },
          '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withNamespace':: d.fn(help="\"Namespace is the namespace of the backend. When unspecified, the local\\nnamespace is inferred.\\n\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { namespace: namespace },
          '#withPort':: d.fn(help='"Port specifies the destination port number to use for this resource.\\nPort is required when the referent is a Kubernetes Service. In this\\ncase, the port number is the service port number, not the target port.\\nFor other resources, destination port might be derived from the referent\\nresource or this field."', args=[d.arg(name='port', type=d.T.integer)]),
          withPort(port): { port: port },
        },
        '#withBackendRefs':: d.fn(help='"BackendRefs references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent.\\nOnly Service kind is supported for now."', args=[d.arg(name='backendRefs', type=d.T.array)]),
        withBackendRefs(backendRefs): { spec+: { extAuth+: { grpc+: { backendRefs: if std.isArray(v=backendRefs) then backendRefs else [backendRefs] } } } },
        '#withBackendRefsMixin':: d.fn(help='"BackendRefs references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent.\\nOnly Service kind is supported for now."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='backendRefs', type=d.T.array)]),
        withBackendRefsMixin(backendRefs): { spec+: { extAuth+: { grpc+: { backendRefs+: if std.isArray(v=backendRefs) then backendRefs else [backendRefs] } } } },
      },
      '#http':: d.obj(help='"HTTP defines the HTTP External Authorization service.\\nEither GRPCService or HTTPService must be specified,\\nand only one of them can be provided."'),
      http: {
        '#backendRef':: d.obj(help='"BackendRef references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent.\\nOnly Service kind is supported for now.\\n\\n\\nDeprecated: Use BackendRefs instead."'),
        backendRef: {
          '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
          withGroup(group): { spec+: { extAuth+: { http+: { backendRef+: { group: group } } } } },
          '#withKind':: d.fn(help='"Kind is the Kubernetes resource kind of the referent. For example\\n\\"Service\\".\\n\\n\\nDefaults to \\"Service\\" when not specified.\\n\\n\\nExternalName services can refer to CNAME DNS records that may live\\noutside of the cluster and as such are difficult to reason about in\\nterms of conformance. They also may not be safe to forward to (see\\nCVE-2021-25740 for more information). Implementations SHOULD NOT\\nsupport ExternalName Services.\\n\\n\\nSupport: Core (Services with a type other than ExternalName)\\n\\n\\nSupport: Implementation-specific (Services with type ExternalName)"', args=[d.arg(name='kind', type=d.T.string)]),
          withKind(kind): { spec+: { extAuth+: { http+: { backendRef+: { kind: kind } } } } },
          '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { extAuth+: { http+: { backendRef+: { name: name } } } } },
          '#withNamespace':: d.fn(help="\"Namespace is the namespace of the backend. When unspecified, the local\\nnamespace is inferred.\\n\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { extAuth+: { http+: { backendRef+: { namespace: namespace } } } } },
          '#withPort':: d.fn(help='"Port specifies the destination port number to use for this resource.\\nPort is required when the referent is a Kubernetes Service. In this\\ncase, the port number is the service port number, not the target port.\\nFor other resources, destination port might be derived from the referent\\nresource or this field."', args=[d.arg(name='port', type=d.T.integer)]),
          withPort(port): { spec+: { extAuth+: { http+: { backendRef+: { port: port } } } } },
        },
        '#backendRefs':: d.obj(help='"BackendRefs references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent.\\nOnly Service kind is supported for now."'),
        backendRefs: {
          '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
          withGroup(group): { group: group },
          '#withKind':: d.fn(help='"Kind is the Kubernetes resource kind of the referent. For example\\n\\"Service\\".\\n\\n\\nDefaults to \\"Service\\" when not specified.\\n\\n\\nExternalName services can refer to CNAME DNS records that may live\\noutside of the cluster and as such are difficult to reason about in\\nterms of conformance. They also may not be safe to forward to (see\\nCVE-2021-25740 for more information). Implementations SHOULD NOT\\nsupport ExternalName Services.\\n\\n\\nSupport: Core (Services with a type other than ExternalName)\\n\\n\\nSupport: Implementation-specific (Services with type ExternalName)"', args=[d.arg(name='kind', type=d.T.string)]),
          withKind(kind): { kind: kind },
          '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withNamespace':: d.fn(help="\"Namespace is the namespace of the backend. When unspecified, the local\\nnamespace is inferred.\\n\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { namespace: namespace },
          '#withPort':: d.fn(help='"Port specifies the destination port number to use for this resource.\\nPort is required when the referent is a Kubernetes Service. In this\\ncase, the port number is the service port number, not the target port.\\nFor other resources, destination port might be derived from the referent\\nresource or this field."', args=[d.arg(name='port', type=d.T.integer)]),
          withPort(port): { port: port },
        },
        '#withBackendRefs':: d.fn(help='"BackendRefs references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent.\\nOnly Service kind is supported for now."', args=[d.arg(name='backendRefs', type=d.T.array)]),
        withBackendRefs(backendRefs): { spec+: { extAuth+: { http+: { backendRefs: if std.isArray(v=backendRefs) then backendRefs else [backendRefs] } } } },
        '#withBackendRefsMixin':: d.fn(help='"BackendRefs references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent.\\nOnly Service kind is supported for now."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='backendRefs', type=d.T.array)]),
        withBackendRefsMixin(backendRefs): { spec+: { extAuth+: { http+: { backendRefs+: if std.isArray(v=backendRefs) then backendRefs else [backendRefs] } } } },
        '#withHeadersToBackend':: d.fn(help='"HeadersToBackend are the authorization response headers that will be added\\nto the original client request before sending it to the backend server.\\nNote that coexisting headers will be overridden.\\nIf not specified, no authorization response headers will be added to the\\noriginal client request."', args=[d.arg(name='headersToBackend', type=d.T.array)]),
        withHeadersToBackend(headersToBackend): { spec+: { extAuth+: { http+: { headersToBackend: if std.isArray(v=headersToBackend) then headersToBackend else [headersToBackend] } } } },
        '#withHeadersToBackendMixin':: d.fn(help='"HeadersToBackend are the authorization response headers that will be added\\nto the original client request before sending it to the backend server.\\nNote that coexisting headers will be overridden.\\nIf not specified, no authorization response headers will be added to the\\noriginal client request."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='headersToBackend', type=d.T.array)]),
        withHeadersToBackendMixin(headersToBackend): { spec+: { extAuth+: { http+: { headersToBackend+: if std.isArray(v=headersToBackend) then headersToBackend else [headersToBackend] } } } },
        '#withPath':: d.fn(help='"Path is the path of the HTTP External Authorization service.\\nIf path is specified, the authorization request will be sent to that path,\\nor else the authorization request will be sent to the root path."', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { spec+: { extAuth+: { http+: { path: path } } } },
      },
      '#withFailOpen':: d.fn(help='"FailOpen is a switch used to control the behavior when a response from the External Authorization service cannot be obtained.\\nIf FailOpen is set to true, the system allows the traffic to pass through.\\nOtherwise, if it is set to false or not set (defaulting to false),\\nthe system blocks the traffic and returns a HTTP 5xx error, reflecting a fail-closed approach.\\nThis setting determines whether to prioritize accessibility over strict security in case of authorization service failure."', args=[d.arg(name='failOpen', type=d.T.boolean)]),
      withFailOpen(failOpen): { spec+: { extAuth+: { failOpen: failOpen } } },
      '#withHeadersToExtAuth':: d.fn(help='"HeadersToExtAuth defines the client request headers that will be included\\nin the request to the external authorization service.\\nNote: If not specified, the default behavior for gRPC and HTTP external\\nauthorization services is different due to backward compatibility reasons.\\nAll headers will be included in the check request to a gRPC authorization server.\\nOnly the following headers will be included in the check request to an HTTP\\nauthorization server: Host, Method, Path, Content-Length, and Authorization.\\nAnd these headers will always be included to the check request to an HTTP\\nauthorization server by default, no matter whether they are specified\\nin HeadersToExtAuth or not."', args=[d.arg(name='headersToExtAuth', type=d.T.array)]),
      withHeadersToExtAuth(headersToExtAuth): { spec+: { extAuth+: { headersToExtAuth: if std.isArray(v=headersToExtAuth) then headersToExtAuth else [headersToExtAuth] } } },
      '#withHeadersToExtAuthMixin':: d.fn(help='"HeadersToExtAuth defines the client request headers that will be included\\nin the request to the external authorization service.\\nNote: If not specified, the default behavior for gRPC and HTTP external\\nauthorization services is different due to backward compatibility reasons.\\nAll headers will be included in the check request to a gRPC authorization server.\\nOnly the following headers will be included in the check request to an HTTP\\nauthorization server: Host, Method, Path, Content-Length, and Authorization.\\nAnd these headers will always be included to the check request to an HTTP\\nauthorization server by default, no matter whether they are specified\\nin HeadersToExtAuth or not."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='headersToExtAuth', type=d.T.array)]),
      withHeadersToExtAuthMixin(headersToExtAuth): { spec+: { extAuth+: { headersToExtAuth+: if std.isArray(v=headersToExtAuth) then headersToExtAuth else [headersToExtAuth] } } },
    },
    '#jwt':: d.obj(help='"JWT defines the configuration for JSON Web Token (JWT) authentication."'),
    jwt: {
      '#providers':: d.obj(help='"Providers defines the JSON Web Token (JWT) authentication provider type.\\nWhen multiple JWT providers are specified, the JWT is considered valid if\\nany of the providers successfully validate the JWT. For additional details,\\nsee https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter.html."'),
      providers: {
        '#claimToHeaders':: d.obj(help='"ClaimToHeaders is a list of JWT claims that must be extracted into HTTP request headers\\nFor examples, following config:\\nThe claim must be of type; string, int, double, bool. Array type claims are not supported"'),
        claimToHeaders: {
          '#withClaim':: d.fn(help='"Claim is the JWT Claim that should be saved into the header : it can be a nested claim of type\\n(eg. \\"claim.nested.key\\", \\"sub\\"). The nested claim name must use dot \\".\\"\\nto separate the JSON name path."', args=[d.arg(name='claim', type=d.T.string)]),
          withClaim(claim): { claim: claim },
          '#withHeader':: d.fn(help='"Header defines the name of the HTTP request header that the JWT Claim will be saved into."', args=[d.arg(name='header', type=d.T.string)]),
          withHeader(header): { header: header },
        },
        '#extractFrom':: d.obj(help='"ExtractFrom defines different ways to extract the JWT token from HTTP request.\\nIf empty, it defaults to extract JWT token from the Authorization HTTP request header using Bearer schema\\nor access_token from query parameters."'),
        extractFrom: {
          '#headers':: d.obj(help='"Headers represents a list of HTTP request headers to extract the JWT token from."'),
          headers: {
            '#withName':: d.fn(help='"Name is the HTTP header name to retrieve the token"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withValuePrefix':: d.fn(help='"ValuePrefix is the prefix that should be stripped before extracting the token.\\nThe format would be used by Envoy like \\"{ValuePrefix}<TOKEN>\\".\\nFor example, \\"Authorization: Bearer <TOKEN>\\", then the ValuePrefix=\\"Bearer \\" with a space at the end."', args=[d.arg(name='valuePrefix', type=d.T.string)]),
            withValuePrefix(valuePrefix): { valuePrefix: valuePrefix },
          },
          '#withCookies':: d.fn(help='"Cookies represents a list of cookie names to extract the JWT token from."', args=[d.arg(name='cookies', type=d.T.array)]),
          withCookies(cookies): { extractFrom+: { cookies: if std.isArray(v=cookies) then cookies else [cookies] } },
          '#withCookiesMixin':: d.fn(help='"Cookies represents a list of cookie names to extract the JWT token from."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='cookies', type=d.T.array)]),
          withCookiesMixin(cookies): { extractFrom+: { cookies+: if std.isArray(v=cookies) then cookies else [cookies] } },
          '#withHeaders':: d.fn(help='"Headers represents a list of HTTP request headers to extract the JWT token from."', args=[d.arg(name='headers', type=d.T.array)]),
          withHeaders(headers): { extractFrom+: { headers: if std.isArray(v=headers) then headers else [headers] } },
          '#withHeadersMixin':: d.fn(help='"Headers represents a list of HTTP request headers to extract the JWT token from."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='headers', type=d.T.array)]),
          withHeadersMixin(headers): { extractFrom+: { headers+: if std.isArray(v=headers) then headers else [headers] } },
          '#withParams':: d.fn(help='"Params represents a list of query parameters to extract the JWT token from."', args=[d.arg(name='params', type=d.T.array)]),
          withParams(params): { extractFrom+: { params: if std.isArray(v=params) then params else [params] } },
          '#withParamsMixin':: d.fn(help='"Params represents a list of query parameters to extract the JWT token from."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='params', type=d.T.array)]),
          withParamsMixin(params): { extractFrom+: { params+: if std.isArray(v=params) then params else [params] } },
        },
        '#remoteJWKS':: d.obj(help='"RemoteJWKS defines how to fetch and cache JSON Web Key Sets (JWKS) from a remote\\nHTTP/HTTPS endpoint."'),
        remoteJWKS: {
          '#withUri':: d.fn(help="\"URI is the HTTPS URI to fetch the JWKS. Envoy's system trust bundle is used to\\nvalidate the server certificate.\"", args=[d.arg(name='uri', type=d.T.string)]),
          withUri(uri): { remoteJWKS+: { uri: uri } },
        },
        '#withAudiences':: d.fn(help='"Audiences is a list of JWT audiences allowed access. For additional details, see\\nhttps://tools.ietf.org/html/rfc7519#section-4.1.3. If not provided, JWT audiences\\nare not checked."', args=[d.arg(name='audiences', type=d.T.array)]),
        withAudiences(audiences): { audiences: if std.isArray(v=audiences) then audiences else [audiences] },
        '#withAudiencesMixin':: d.fn(help='"Audiences is a list of JWT audiences allowed access. For additional details, see\\nhttps://tools.ietf.org/html/rfc7519#section-4.1.3. If not provided, JWT audiences\\nare not checked."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='audiences', type=d.T.array)]),
        withAudiencesMixin(audiences): { audiences+: if std.isArray(v=audiences) then audiences else [audiences] },
        '#withClaimToHeaders':: d.fn(help='"ClaimToHeaders is a list of JWT claims that must be extracted into HTTP request headers\\nFor examples, following config:\\nThe claim must be of type; string, int, double, bool. Array type claims are not supported"', args=[d.arg(name='claimToHeaders', type=d.T.array)]),
        withClaimToHeaders(claimToHeaders): { claimToHeaders: if std.isArray(v=claimToHeaders) then claimToHeaders else [claimToHeaders] },
        '#withClaimToHeadersMixin':: d.fn(help='"ClaimToHeaders is a list of JWT claims that must be extracted into HTTP request headers\\nFor examples, following config:\\nThe claim must be of type; string, int, double, bool. Array type claims are not supported"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='claimToHeaders', type=d.T.array)]),
        withClaimToHeadersMixin(claimToHeaders): { claimToHeaders+: if std.isArray(v=claimToHeaders) then claimToHeaders else [claimToHeaders] },
        '#withIssuer':: d.fn(help='"Issuer is the principal that issued the JWT and takes the form of a URL or email address.\\nFor additional details, see https://tools.ietf.org/html/rfc7519#section-4.1.1 for\\nURL format and https://rfc-editor.org/rfc/rfc5322.html for email format. If not provided,\\nthe JWT issuer is not checked."', args=[d.arg(name='issuer', type=d.T.string)]),
        withIssuer(issuer): { issuer: issuer },
        '#withName':: d.fn(help='"Name defines a unique name for the JWT provider. A name can have a variety of forms,\\nincluding RFC1123 subdomains, RFC 1123 labels, or RFC 1035 labels."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withRecomputeRoute':: d.fn(help='"RecomputeRoute clears the route cache and recalculates the routing decision.\\nThis field must be enabled if the headers generated from the claim are used for\\nroute matching decisions. If the recomputation selects a new route, features targeting\\nthe new matched route will be applied."', args=[d.arg(name='recomputeRoute', type=d.T.boolean)]),
        withRecomputeRoute(recomputeRoute): { recomputeRoute: recomputeRoute },
      },
      '#withOptional':: d.fn(help='"Optional determines whether a missing JWT is acceptable, defaulting to false if not specified.\\nNote: Even if optional is set to true, JWT authentication will still fail if an invalid JWT is presented."', args=[d.arg(name='optional', type=d.T.boolean)]),
      withOptional(optional): { spec+: { jwt+: { optional: optional } } },
      '#withProviders':: d.fn(help='"Providers defines the JSON Web Token (JWT) authentication provider type.\\nWhen multiple JWT providers are specified, the JWT is considered valid if\\nany of the providers successfully validate the JWT. For additional details,\\nsee https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter.html."', args=[d.arg(name='providers', type=d.T.array)]),
      withProviders(providers): { spec+: { jwt+: { providers: if std.isArray(v=providers) then providers else [providers] } } },
      '#withProvidersMixin':: d.fn(help='"Providers defines the JSON Web Token (JWT) authentication provider type.\\nWhen multiple JWT providers are specified, the JWT is considered valid if\\nany of the providers successfully validate the JWT. For additional details,\\nsee https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter.html."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='providers', type=d.T.array)]),
      withProvidersMixin(providers): { spec+: { jwt+: { providers+: if std.isArray(v=providers) then providers else [providers] } } },
    },
    '#oidc':: d.obj(help='"OIDC defines the configuration for the OpenID Connect (OIDC) authentication."'),
    oidc: {
      '#clientSecret':: d.obj(help='"The Kubernetes secret which contains the OIDC client secret to be used in the\\n[Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).\\n\\n\\nThis is an Opaque secret. The client secret should be stored in the key\\n\\"client-secret\\"."'),
      clientSecret: {
        '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
        withGroup(group): { spec+: { oidc+: { clientSecret+: { group: group } } } },
        '#withKind':: d.fn(help='"Kind is kind of the referent. For example \\"Secret\\"."', args=[d.arg(name='kind', type=d.T.string)]),
        withKind(kind): { spec+: { oidc+: { clientSecret+: { kind: kind } } } },
        '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { oidc+: { clientSecret+: { name: name } } } },
        '#withNamespace':: d.fn(help="\"Namespace is the namespace of the referenced object. When unspecified, the local\\nnamespace is inferred.\\n\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { oidc+: { clientSecret+: { namespace: namespace } } } },
      },
      '#cookieNames':: d.obj(help='"The optional cookie name overrides to be used for Bearer and IdToken cookies in the\\n[Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).\\nIf not specified, uses a randomly generated suffix"'),
      cookieNames: {
        '#withAccessToken':: d.fn(help='"The name of the cookie used to store the AccessToken in the\\n[Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).\\nIf not specified, defaults to \\"AccessToken-(randomly generated uid)\\', args=[d.arg(name='accessToken', type=d.T.string)]),
        withAccessToken(accessToken): { spec+: { oidc+: { cookieNames+: { accessToken: accessToken } } } },
        '#withIdToken':: d.fn(help='"The name of the cookie used to store the IdToken in the\\n[Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).\\nIf not specified, defaults to \\"IdToken-(randomly generated uid)\\', args=[d.arg(name='idToken', type=d.T.string)]),
        withIdToken(idToken): { spec+: { oidc+: { cookieNames+: { idToken: idToken } } } },
      },
      '#provider':: d.obj(help='"The OIDC Provider configuration."'),
      provider: {
        '#withAuthorizationEndpoint':: d.fn(help="\"The OIDC Provider's [authorization endpoint](https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint).\\nIf not provided, EG will try to discover it from the provider's [Well-Known Configuration Endpoint](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse).\"", args=[d.arg(name='authorizationEndpoint', type=d.T.string)]),
        withAuthorizationEndpoint(authorizationEndpoint): { spec+: { oidc+: { provider+: { authorizationEndpoint: authorizationEndpoint } } } },
        '#withIssuer':: d.fn(help="\"The OIDC Provider's [issuer identifier](https://openid.net/specs/openid-connect-discovery-1_0.html#IssuerDiscovery).\\nIssuer MUST be a URI RFC 3986 [RFC3986] with a scheme component that MUST\\nbe https, a host component, and optionally, port and path components and\\nno query or fragment components.\"", args=[d.arg(name='issuer', type=d.T.string)]),
        withIssuer(issuer): { spec+: { oidc+: { provider+: { issuer: issuer } } } },
        '#withTokenEndpoint':: d.fn(help="\"The OIDC Provider's [token endpoint](https://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint).\\nIf not provided, EG will try to discover it from the provider's [Well-Known Configuration Endpoint](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse).\"", args=[d.arg(name='tokenEndpoint', type=d.T.string)]),
        withTokenEndpoint(tokenEndpoint): { spec+: { oidc+: { provider+: { tokenEndpoint: tokenEndpoint } } } },
      },
      '#withClientID':: d.fn(help='"The client ID to be used in the OIDC\\n[Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)."', args=[d.arg(name='clientID', type=d.T.string)]),
      withClientID(clientID): { spec+: { oidc+: { clientID: clientID } } },
      '#withDefaultRefreshTokenTTL':: d.fn(help='"DefaultRefreshTokenTTL is the default lifetime of the refresh token.\\nThis field is only used when the exp (expiration time) claim is omitted in\\nthe refresh token or the refresh token is not JWT.\\n\\n\\nIf not specified, defaults to 604800s (one week).\\nNote: this field is only applicable when the \\"refreshToken\\" field is set to true."', args=[d.arg(name='defaultRefreshTokenTTL', type=d.T.string)]),
      withDefaultRefreshTokenTTL(defaultRefreshTokenTTL): { spec+: { oidc+: { defaultRefreshTokenTTL: defaultRefreshTokenTTL } } },
      '#withDefaultTokenTTL':: d.fn(help='"DefaultTokenTTL is the default lifetime of the id token and access token.\\nPlease note that Envoy will always use the expiry time from the response\\nof the authorization server if it is provided. This field is only used when\\nthe expiry time is not provided by the authorization.\\n\\n\\nIf not specified, defaults to 0. In this case, the \\"expires_in\\" field in\\nthe authorization response must be set by the authorization server, or the\\nOAuth flow will fail."', args=[d.arg(name='defaultTokenTTL', type=d.T.string)]),
      withDefaultTokenTTL(defaultTokenTTL): { spec+: { oidc+: { defaultTokenTTL: defaultTokenTTL } } },
      '#withForwardAccessToken':: d.fn(help='"ForwardAccessToken indicates whether the Envoy should forward the access token\\nvia the Authorization header Bearer scheme to the upstream.\\nIf not specified, defaults to false."', args=[d.arg(name='forwardAccessToken', type=d.T.boolean)]),
      withForwardAccessToken(forwardAccessToken): { spec+: { oidc+: { forwardAccessToken: forwardAccessToken } } },
      '#withLogoutPath':: d.fn(help='"The path to log a user out, clearing their credential cookies.\\n\\n\\nIf not specified, uses a default logout path \\"/logout\\', args=[d.arg(name='logoutPath', type=d.T.string)]),
      withLogoutPath(logoutPath): { spec+: { oidc+: { logoutPath: logoutPath } } },
      '#withRedirectURL':: d.fn(help='"The redirect URL to be used in the OIDC\\n[Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).\\nIf not specified, uses the default redirect URI \\"%REQ(x-forwarded-proto)%://%REQ(:authority)%/oauth2/callback\\', args=[d.arg(name='redirectURL', type=d.T.string)]),
      withRedirectURL(redirectURL): { spec+: { oidc+: { redirectURL: redirectURL } } },
      '#withRefreshToken':: d.fn(help='"RefreshToken indicates whether the Envoy should automatically refresh the\\nid token and access token when they expire.\\nWhen set to true, the Envoy will use the refresh token to get a new id token\\nand access token when they expire.\\n\\n\\nIf not specified, defaults to false."', args=[d.arg(name='refreshToken', type=d.T.boolean)]),
      withRefreshToken(refreshToken): { spec+: { oidc+: { refreshToken: refreshToken } } },
      '#withResources':: d.fn(help='"The OIDC resources to be used in the\\n[Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)."', args=[d.arg(name='resources', type=d.T.array)]),
      withResources(resources): { spec+: { oidc+: { resources: if std.isArray(v=resources) then resources else [resources] } } },
      '#withResourcesMixin':: d.fn(help='"The OIDC resources to be used in the\\n[Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='resources', type=d.T.array)]),
      withResourcesMixin(resources): { spec+: { oidc+: { resources+: if std.isArray(v=resources) then resources else [resources] } } },
      '#withScopes':: d.fn(help='"The OIDC scopes to be used in the\\n[Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).\\nThe \\"openid\\" scope is always added to the list of scopes if not already\\nspecified."', args=[d.arg(name='scopes', type=d.T.array)]),
      withScopes(scopes): { spec+: { oidc+: { scopes: if std.isArray(v=scopes) then scopes else [scopes] } } },
      '#withScopesMixin':: d.fn(help='"The OIDC scopes to be used in the\\n[Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).\\nThe \\"openid\\" scope is always added to the list of scopes if not already\\nspecified."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scopes', type=d.T.array)]),
      withScopesMixin(scopes): { spec+: { oidc+: { scopes+: if std.isArray(v=scopes) then scopes else [scopes] } } },
    },
    '#targetRef':: d.obj(help='"TargetRef is the name of the resource this policy is being attached to.\\nThis policy and the TargetRef MUST be in the same namespace for this\\nPolicy to have effect\\n\\n\\nDeprecated: use targetRefs/targetSelectors instead"'),
    targetRef: {
      '#withGroup':: d.fn(help='"Group is the group of the target resource."', args=[d.arg(name='group', type=d.T.string)]),
      withGroup(group): { spec+: { targetRef+: { group: group } } },
      '#withKind':: d.fn(help='"Kind is kind of the target resource."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { targetRef+: { kind: kind } } },
      '#withName':: d.fn(help='"Name is the name of the target resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { targetRef+: { name: name } } },
      '#withSectionName':: d.fn(help="\"SectionName is the name of a section within the target resource. When\\nunspecified, this targetRef targets the entire resource. In the following\\nresources, SectionName is interpreted as the following:\\n\\n\\n* Gateway: Listener name\\n* HTTPRoute: HTTPRouteRule name\\n* Service: Port name\\n\\n\\nIf a SectionName is specified, but does not exist on the targeted object,\\nthe Policy must fail to attach, and the policy implementation should record\\na `ResolvedRefs` or similar Condition in the Policy's status.\"", args=[d.arg(name='sectionName', type=d.T.string)]),
      withSectionName(sectionName): { spec+: { targetRef+: { sectionName: sectionName } } },
    },
    '#targetRefs':: d.obj(help='"TargetRefs are the names of the Gateway resources this policy\\nis being attached to."'),
    targetRefs: {
      '#withGroup':: d.fn(help='"Group is the group of the target resource."', args=[d.arg(name='group', type=d.T.string)]),
      withGroup(group): { group: group },
      '#withKind':: d.fn(help='"Kind is kind of the target resource."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { kind: kind },
      '#withName':: d.fn(help='"Name is the name of the target resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withSectionName':: d.fn(help="\"SectionName is the name of a section within the target resource. When\\nunspecified, this targetRef targets the entire resource. In the following\\nresources, SectionName is interpreted as the following:\\n\\n\\n* Gateway: Listener name\\n* HTTPRoute: HTTPRouteRule name\\n* Service: Port name\\n\\n\\nIf a SectionName is specified, but does not exist on the targeted object,\\nthe Policy must fail to attach, and the policy implementation should record\\na `ResolvedRefs` or similar Condition in the Policy's status.\"", args=[d.arg(name='sectionName', type=d.T.string)]),
      withSectionName(sectionName): { sectionName: sectionName },
    },
    '#targetSelectors':: d.obj(help='"TargetSelectors allow targeting resources for this policy based on labels"'),
    targetSelectors: {
      '#withGroup':: d.fn(help='"Group is the group that this selector targets. Defaults to gateway.networking.k8s.io"', args=[d.arg(name='group', type=d.T.string)]),
      withGroup(group): { group: group },
      '#withKind':: d.fn(help='"Kind is the resource kind that this selector targets."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { kind: kind },
      '#withMatchLabels':: d.fn(help='"MatchLabels are the set of label selectors for identifying the targeted resource"', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { matchLabels: matchLabels },
      '#withMatchLabelsMixin':: d.fn(help='"MatchLabels are the set of label selectors for identifying the targeted resource"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { matchLabels+: matchLabels },
    },
    '#withTargetRefs':: d.fn(help='"TargetRefs are the names of the Gateway resources this policy\\nis being attached to."', args=[d.arg(name='targetRefs', type=d.T.array)]),
    withTargetRefs(targetRefs): { spec+: { targetRefs: if std.isArray(v=targetRefs) then targetRefs else [targetRefs] } },
    '#withTargetRefsMixin':: d.fn(help='"TargetRefs are the names of the Gateway resources this policy\\nis being attached to."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetRefs', type=d.T.array)]),
    withTargetRefsMixin(targetRefs): { spec+: { targetRefs+: if std.isArray(v=targetRefs) then targetRefs else [targetRefs] } },
    '#withTargetSelectors':: d.fn(help='"TargetSelectors allow targeting resources for this policy based on labels"', args=[d.arg(name='targetSelectors', type=d.T.array)]),
    withTargetSelectors(targetSelectors): { spec+: { targetSelectors: if std.isArray(v=targetSelectors) then targetSelectors else [targetSelectors] } },
    '#withTargetSelectorsMixin':: d.fn(help='"TargetSelectors allow targeting resources for this policy based on labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetSelectors', type=d.T.array)]),
    withTargetSelectorsMixin(targetSelectors): { spec+: { targetSelectors+: if std.isArray(v=targetSelectors) then targetSelectors else [targetSelectors] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
