{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='envoyExtensionPolicy', url='', help='"EnvoyExtensionPolicy allows the user to configure various envoy extensibility options for the Gateway."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of EnvoyExtensionPolicy', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'gateway.envoyproxy.io/v1alpha1',
    kind: 'EnvoyExtensionPolicy',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"Spec defines the desired state of EnvoyExtensionPolicy."'),
  spec: {
    '#extProc':: d.obj(help='"ExtProc is an ordered list of external processing filters\\nthat should be added to the envoy filter chain"'),
    extProc: {
      '#backendRef':: d.obj(help='"BackendRef references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent.\\n\\nDeprecated: Use BackendRefs instead."'),
      backendRef: {
        '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
        withGroup(group): { backendRef+: { group: group } },
        '#withKind':: d.fn(help='"Kind is the Kubernetes resource kind of the referent. For example\\n\\"Service\\".\\n\\nDefaults to \\"Service\\" when not specified.\\n\\nExternalName services can refer to CNAME DNS records that may live\\noutside of the cluster and as such are difficult to reason about in\\nterms of conformance. They also may not be safe to forward to (see\\nCVE-2021-25740 for more information). Implementations SHOULD NOT\\nsupport ExternalName Services.\\n\\nSupport: Core (Services with a type other than ExternalName)\\n\\nSupport: Implementation-specific (Services with type ExternalName)"', args=[d.arg(name='kind', type=d.T.string)]),
        withKind(kind): { backendRef+: { kind: kind } },
        '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { backendRef+: { name: name } },
        '#withNamespace':: d.fn(help="\"Namespace is the namespace of the backend. When unspecified, the local\\nnamespace is inferred.\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { backendRef+: { namespace: namespace } },
        '#withPort':: d.fn(help='"Port specifies the destination port number to use for this resource.\\nPort is required when the referent is a Kubernetes Service. In this\\ncase, the port number is the service port number, not the target port.\\nFor other resources, destination port might be derived from the referent\\nresource or this field."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { backendRef+: { port: port } },
      },
      '#backendRefs':: d.obj(help='"BackendRefs references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent."'),
      backendRefs: {
        '#withFallback':: d.fn(help='"Fallback indicates whether the backend is designated as a fallback.\\nMultiple fallback backends can be configured.\\nIt is highly recommended to configure active or passive health checks to ensure that failover can be detected\\nwhen the active backends become unhealthy and to automatically readjust once the primary backends are healthy again.\\nThe overprovisioning factor is set to 1.4, meaning the fallback backends will only start receiving traffic when\\nthe health of the active backends falls below 72%."', args=[d.arg(name='fallback', type=d.T.boolean)]),
        withFallback(fallback): { fallback: fallback },
        '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
        withGroup(group): { group: group },
        '#withKind':: d.fn(help='"Kind is the Kubernetes resource kind of the referent. For example\\n\\"Service\\".\\n\\nDefaults to \\"Service\\" when not specified.\\n\\nExternalName services can refer to CNAME DNS records that may live\\noutside of the cluster and as such are difficult to reason about in\\nterms of conformance. They also may not be safe to forward to (see\\nCVE-2021-25740 for more information). Implementations SHOULD NOT\\nsupport ExternalName Services.\\n\\nSupport: Core (Services with a type other than ExternalName)\\n\\nSupport: Implementation-specific (Services with type ExternalName)"', args=[d.arg(name='kind', type=d.T.string)]),
        withKind(kind): { kind: kind },
        '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withNamespace':: d.fn(help="\"Namespace is the namespace of the backend. When unspecified, the local\\nnamespace is inferred.\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { namespace: namespace },
        '#withPort':: d.fn(help='"Port specifies the destination port number to use for this resource.\\nPort is required when the referent is a Kubernetes Service. In this\\ncase, the port number is the service port number, not the target port.\\nFor other resources, destination port might be derived from the referent\\nresource or this field."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { port: port },
      },
      '#backendSettings':: d.obj(help='"BackendSettings holds configuration for managing the connection\\nto the backend."'),
      backendSettings: {
        '#circuitBreaker':: d.obj(help='"Circuit Breaker settings for the upstream connections and requests.\\nIf not set, circuit breakers will be enabled with the default thresholds"'),
        circuitBreaker: {
          '#withMaxConnections':: d.fn(help='"The maximum number of connections that Envoy will establish to the referenced backend defined within a xRoute rule."', args=[d.arg(name='maxConnections', type=d.T.integer)]),
          withMaxConnections(maxConnections): { backendSettings+: { circuitBreaker+: { maxConnections: maxConnections } } },
          '#withMaxParallelRequests':: d.fn(help='"The maximum number of parallel requests that Envoy will make to the referenced backend defined within a xRoute rule."', args=[d.arg(name='maxParallelRequests', type=d.T.integer)]),
          withMaxParallelRequests(maxParallelRequests): { backendSettings+: { circuitBreaker+: { maxParallelRequests: maxParallelRequests } } },
          '#withMaxParallelRetries':: d.fn(help='"The maximum number of parallel retries that Envoy will make to the referenced backend defined within a xRoute rule."', args=[d.arg(name='maxParallelRetries', type=d.T.integer)]),
          withMaxParallelRetries(maxParallelRetries): { backendSettings+: { circuitBreaker+: { maxParallelRetries: maxParallelRetries } } },
          '#withMaxPendingRequests':: d.fn(help='"The maximum number of pending requests that Envoy will queue to the referenced backend defined within a xRoute rule."', args=[d.arg(name='maxPendingRequests', type=d.T.integer)]),
          withMaxPendingRequests(maxPendingRequests): { backendSettings+: { circuitBreaker+: { maxPendingRequests: maxPendingRequests } } },
          '#withMaxRequestsPerConnection':: d.fn(help='"The maximum number of requests that Envoy will make over a single connection to the referenced backend defined within a xRoute rule.\\nDefault: unlimited."', args=[d.arg(name='maxRequestsPerConnection', type=d.T.integer)]),
          withMaxRequestsPerConnection(maxRequestsPerConnection): { backendSettings+: { circuitBreaker+: { maxRequestsPerConnection: maxRequestsPerConnection } } },
        },
        '#connection':: d.obj(help='"Connection includes backend connection settings."'),
        connection: {
          '#withBufferLimit':: d.fn(help="\"BufferLimit Soft limit on size of the cluster’s connections read and write buffers.\\nBufferLimit applies to connection streaming (maybe non-streaming) channel between processes, it's in user space.\\nIf unspecified, an implementation defined default is applied (32768 bytes).\\nFor example, 20Mi, 1Gi, 256Ki etc.\\nNote: that when the suffix is not provided, the value is interpreted as bytes.\"", args=[d.arg(name='bufferLimit', type=d.T.any)]),
          withBufferLimit(bufferLimit): { backendSettings+: { connection+: { bufferLimit: bufferLimit } } },
          '#withSocketBufferLimit':: d.fn(help="\"SocketBufferLimit provides configuration for the maximum buffer size in bytes for each socket\\nto backend.\\nSocketBufferLimit applies to socket streaming channel between TCP/IP stacks, it's in kernel space.\\nFor example, 20Mi, 1Gi, 256Ki etc.\\nNote that when the suffix is not provided, the value is interpreted as bytes.\"", args=[d.arg(name='socketBufferLimit', type=d.T.any)]),
          withSocketBufferLimit(socketBufferLimit): { backendSettings+: { connection+: { socketBufferLimit: socketBufferLimit } } },
        },
        '#dns':: d.obj(help='"DNS includes dns resolution settings."'),
        dns: {
          '#withDnsRefreshRate':: d.fn(help='"DNSRefreshRate specifies the rate at which DNS records should be refreshed.\\nDefaults to 30 seconds."', args=[d.arg(name='dnsRefreshRate', type=d.T.string)]),
          withDnsRefreshRate(dnsRefreshRate): { backendSettings+: { dns+: { dnsRefreshRate: dnsRefreshRate } } },
          '#withRespectDnsTtl':: d.fn(help='"RespectDNSTTL indicates whether the DNS Time-To-Live (TTL) should be respected.\\nIf the value is set to true, the DNS refresh rate will be set to the resource record’s TTL.\\nDefaults to true."', args=[d.arg(name='respectDnsTtl', type=d.T.boolean)]),
          withRespectDnsTtl(respectDnsTtl): { backendSettings+: { dns+: { respectDnsTtl: respectDnsTtl } } },
        },
        '#healthCheck':: d.obj(help='"HealthCheck allows gateway to perform active health checking on backends."'),
        healthCheck: {
          '#active':: d.obj(help='"Active health check configuration"'),
          active: {
            '#grpc':: d.obj(help="\"GRPC defines the configuration of the GRPC health checker.\\nIt's optional, and can only be used if the specified type is GRPC.\""),
            grpc: {
              '#withService':: d.fn(help='"Service to send in the health check request.\\nIf this is not specified, then the health check request applies to the entire\\nserver and not to a specific service."', args=[d.arg(name='service', type=d.T.string)]),
              withService(service): { backendSettings+: { healthCheck+: { active+: { grpc+: { service: service } } } } },
            },
            '#http':: d.obj(help="\"HTTP defines the configuration of http health checker.\\nIt's required while the health checker type is HTTP.\""),
            http: {
              '#expectedResponse':: d.obj(help='"ExpectedResponse defines a list of HTTP expected responses to match."'),
              expectedResponse: {
                '#withBinary':: d.fn(help='"Binary payload base64 encoded."', args=[d.arg(name='binary', type=d.T.string)]),
                withBinary(binary): { backendSettings+: { healthCheck+: { active+: { http+: { expectedResponse+: { binary: binary } } } } } },
                '#withText':: d.fn(help='"Text payload in plain text."', args=[d.arg(name='text', type=d.T.string)]),
                withText(text): { backendSettings+: { healthCheck+: { active+: { http+: { expectedResponse+: { text: text } } } } } },
                '#withType':: d.fn(help='"Type defines the type of the payload."', args=[d.arg(name='type', type=d.T.string)]),
                withType(type): { backendSettings+: { healthCheck+: { active+: { http+: { expectedResponse+: { type: type } } } } } },
              },
              '#withExpectedStatuses':: d.fn(help='"ExpectedStatuses defines a list of HTTP response statuses considered healthy.\\nDefaults to 200 only"', args=[d.arg(name='expectedStatuses', type=d.T.array)]),
              withExpectedStatuses(expectedStatuses): { backendSettings+: { healthCheck+: { active+: { http+: { expectedStatuses: if std.isArray(v=expectedStatuses) then expectedStatuses else [expectedStatuses] } } } } },
              '#withExpectedStatusesMixin':: d.fn(help='"ExpectedStatuses defines a list of HTTP response statuses considered healthy.\\nDefaults to 200 only"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='expectedStatuses', type=d.T.array)]),
              withExpectedStatusesMixin(expectedStatuses): { backendSettings+: { healthCheck+: { active+: { http+: { expectedStatuses+: if std.isArray(v=expectedStatuses) then expectedStatuses else [expectedStatuses] } } } } },
              '#withMethod':: d.fn(help='"Method defines the HTTP method used for health checking.\\nDefaults to GET"', args=[d.arg(name='method', type=d.T.string)]),
              withMethod(method): { backendSettings+: { healthCheck+: { active+: { http+: { method: method } } } } },
              '#withPath':: d.fn(help='"Path defines the HTTP path that will be requested during health checking."', args=[d.arg(name='path', type=d.T.string)]),
              withPath(path): { backendSettings+: { healthCheck+: { active+: { http+: { path: path } } } } },
            },
            '#tcp':: d.obj(help="\"TCP defines the configuration of tcp health checker.\\nIt's required while the health checker type is TCP.\""),
            tcp: {
              '#receive':: d.obj(help='"Receive defines the expected response payload."'),
              receive: {
                '#withBinary':: d.fn(help='"Binary payload base64 encoded."', args=[d.arg(name='binary', type=d.T.string)]),
                withBinary(binary): { backendSettings+: { healthCheck+: { active+: { tcp+: { receive+: { binary: binary } } } } } },
                '#withText':: d.fn(help='"Text payload in plain text."', args=[d.arg(name='text', type=d.T.string)]),
                withText(text): { backendSettings+: { healthCheck+: { active+: { tcp+: { receive+: { text: text } } } } } },
                '#withType':: d.fn(help='"Type defines the type of the payload."', args=[d.arg(name='type', type=d.T.string)]),
                withType(type): { backendSettings+: { healthCheck+: { active+: { tcp+: { receive+: { type: type } } } } } },
              },
              '#send':: d.obj(help='"Send defines the request payload."'),
              send: {
                '#withBinary':: d.fn(help='"Binary payload base64 encoded."', args=[d.arg(name='binary', type=d.T.string)]),
                withBinary(binary): { backendSettings+: { healthCheck+: { active+: { tcp+: { send+: { binary: binary } } } } } },
                '#withText':: d.fn(help='"Text payload in plain text."', args=[d.arg(name='text', type=d.T.string)]),
                withText(text): { backendSettings+: { healthCheck+: { active+: { tcp+: { send+: { text: text } } } } } },
                '#withType':: d.fn(help='"Type defines the type of the payload."', args=[d.arg(name='type', type=d.T.string)]),
                withType(type): { backendSettings+: { healthCheck+: { active+: { tcp+: { send+: { type: type } } } } } },
              },
            },
            '#withHealthyThreshold':: d.fn(help='"HealthyThreshold defines the number of healthy health checks required before a backend host is marked healthy."', args=[d.arg(name='healthyThreshold', type=d.T.integer)]),
            withHealthyThreshold(healthyThreshold): { backendSettings+: { healthCheck+: { active+: { healthyThreshold: healthyThreshold } } } },
            '#withInterval':: d.fn(help='"Interval defines the time between active health checks."', args=[d.arg(name='interval', type=d.T.string)]),
            withInterval(interval): { backendSettings+: { healthCheck+: { active+: { interval: interval } } } },
            '#withTimeout':: d.fn(help='"Timeout defines the time to wait for a health check response."', args=[d.arg(name='timeout', type=d.T.string)]),
            withTimeout(timeout): { backendSettings+: { healthCheck+: { active+: { timeout: timeout } } } },
            '#withType':: d.fn(help='"Type defines the type of health checker."', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { backendSettings+: { healthCheck+: { active+: { type: type } } } },
            '#withUnhealthyThreshold':: d.fn(help='"UnhealthyThreshold defines the number of unhealthy health checks required before a backend host is marked unhealthy."', args=[d.arg(name='unhealthyThreshold', type=d.T.integer)]),
            withUnhealthyThreshold(unhealthyThreshold): { backendSettings+: { healthCheck+: { active+: { unhealthyThreshold: unhealthyThreshold } } } },
          },
          '#passive':: d.obj(help='"Passive passive check configuration"'),
          passive: {
            '#withBaseEjectionTime':: d.fn(help='"BaseEjectionTime defines the base duration for which a host will be ejected on consecutive failures."', args=[d.arg(name='baseEjectionTime', type=d.T.string)]),
            withBaseEjectionTime(baseEjectionTime): { backendSettings+: { healthCheck+: { passive+: { baseEjectionTime: baseEjectionTime } } } },
            '#withConsecutive5XxErrors':: d.fn(help='"Consecutive5xxErrors sets the number of consecutive 5xx errors triggering ejection."', args=[d.arg(name='consecutive5XxErrors', type=d.T.integer)]),
            withConsecutive5XxErrors(consecutive5XxErrors): { backendSettings+: { healthCheck+: { passive+: { consecutive5XxErrors: consecutive5XxErrors } } } },
            '#withConsecutiveGatewayErrors':: d.fn(help='"ConsecutiveGatewayErrors sets the number of consecutive gateway errors triggering ejection."', args=[d.arg(name='consecutiveGatewayErrors', type=d.T.integer)]),
            withConsecutiveGatewayErrors(consecutiveGatewayErrors): { backendSettings+: { healthCheck+: { passive+: { consecutiveGatewayErrors: consecutiveGatewayErrors } } } },
            '#withConsecutiveLocalOriginFailures':: d.fn(help='"ConsecutiveLocalOriginFailures sets the number of consecutive local origin failures triggering ejection.\\nParameter takes effect only when split_external_local_origin_errors is set to true."', args=[d.arg(name='consecutiveLocalOriginFailures', type=d.T.integer)]),
            withConsecutiveLocalOriginFailures(consecutiveLocalOriginFailures): { backendSettings+: { healthCheck+: { passive+: { consecutiveLocalOriginFailures: consecutiveLocalOriginFailures } } } },
            '#withInterval':: d.fn(help='"Interval defines the time between passive health checks."', args=[d.arg(name='interval', type=d.T.string)]),
            withInterval(interval): { backendSettings+: { healthCheck+: { passive+: { interval: interval } } } },
            '#withMaxEjectionPercent':: d.fn(help='"MaxEjectionPercent sets the maximum percentage of hosts in a cluster that can be ejected."', args=[d.arg(name='maxEjectionPercent', type=d.T.integer)]),
            withMaxEjectionPercent(maxEjectionPercent): { backendSettings+: { healthCheck+: { passive+: { maxEjectionPercent: maxEjectionPercent } } } },
            '#withSplitExternalLocalOriginErrors':: d.fn(help='"SplitExternalLocalOriginErrors enables splitting of errors between external and local origin."', args=[d.arg(name='splitExternalLocalOriginErrors', type=d.T.boolean)]),
            withSplitExternalLocalOriginErrors(splitExternalLocalOriginErrors): { backendSettings+: { healthCheck+: { passive+: { splitExternalLocalOriginErrors: splitExternalLocalOriginErrors } } } },
          },
        },
        '#http2':: d.obj(help='"HTTP2 provides HTTP/2 configuration for backend connections."'),
        http2: {
          '#withInitialConnectionWindowSize':: d.fn(help='"InitialConnectionWindowSize sets the initial window size for HTTP/2 connections.\\nIf not set, the default value is 1 MiB."', args=[d.arg(name='initialConnectionWindowSize', type=d.T.any)]),
          withInitialConnectionWindowSize(initialConnectionWindowSize): { backendSettings+: { http2+: { initialConnectionWindowSize: initialConnectionWindowSize } } },
          '#withInitialStreamWindowSize':: d.fn(help='"InitialStreamWindowSize sets the initial window size for HTTP/2 streams.\\nIf not set, the default value is 64 KiB(64*1024)."', args=[d.arg(name='initialStreamWindowSize', type=d.T.any)]),
          withInitialStreamWindowSize(initialStreamWindowSize): { backendSettings+: { http2+: { initialStreamWindowSize: initialStreamWindowSize } } },
          '#withMaxConcurrentStreams':: d.fn(help='"MaxConcurrentStreams sets the maximum number of concurrent streams allowed per connection.\\nIf not set, the default value is 100."', args=[d.arg(name='maxConcurrentStreams', type=d.T.integer)]),
          withMaxConcurrentStreams(maxConcurrentStreams): { backendSettings+: { http2+: { maxConcurrentStreams: maxConcurrentStreams } } },
          '#withOnInvalidMessage':: d.fn(help="\"OnInvalidMessage determines if Envoy will terminate the connection or just the offending stream in the event of HTTP messaging error\\nIt's recommended for L2 Envoy deployments to set this value to TerminateStream.\\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/level_two\\nDefault: TerminateConnection\"", args=[d.arg(name='onInvalidMessage', type=d.T.string)]),
          withOnInvalidMessage(onInvalidMessage): { backendSettings+: { http2+: { onInvalidMessage: onInvalidMessage } } },
        },
        '#loadBalancer':: d.obj(help='"LoadBalancer policy to apply when routing traffic from the gateway to\\nthe backend endpoints. Defaults to `LeastRequest`."'),
        loadBalancer: {
          '#consistentHash':: d.obj(help='"ConsistentHash defines the configuration when the load balancer type is\\nset to ConsistentHash"'),
          consistentHash: {
            '#cookie':: d.obj(help='"Cookie configures the cookie hash policy when the consistent hash type is set to Cookie."'),
            cookie: {
              '#withAttributes':: d.fn(help='"Additional Attributes to set for the generated cookie."', args=[d.arg(name='attributes', type=d.T.object)]),
              withAttributes(attributes): { backendSettings+: { loadBalancer+: { consistentHash+: { cookie+: { attributes: attributes } } } } },
              '#withAttributesMixin':: d.fn(help='"Additional Attributes to set for the generated cookie."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='attributes', type=d.T.object)]),
              withAttributesMixin(attributes): { backendSettings+: { loadBalancer+: { consistentHash+: { cookie+: { attributes+: attributes } } } } },
              '#withName':: d.fn(help='"Name of the cookie to hash.\\nIf this cookie does not exist in the request, Envoy will generate a cookie and set\\nthe TTL on the response back to the client based on Layer 4\\nattributes of the backend endpoint, to ensure that these future requests\\ngo to the same backend endpoint. Make sure to set the TTL field for this case."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { backendSettings+: { loadBalancer+: { consistentHash+: { cookie+: { name: name } } } } },
              '#withTtl':: d.fn(help='"TTL of the generated cookie if the cookie is not present. This value sets the\\nMax-Age attribute value."', args=[d.arg(name='ttl', type=d.T.string)]),
              withTtl(ttl): { backendSettings+: { loadBalancer+: { consistentHash+: { cookie+: { ttl: ttl } } } } },
            },
            '#header':: d.obj(help='"Header configures the header hash policy when the consistent hash type is set to Header."'),
            header: {
              '#withName':: d.fn(help='"Name of the header to hash."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { backendSettings+: { loadBalancer+: { consistentHash+: { header+: { name: name } } } } },
            },
            '#withTableSize':: d.fn(help='"The table size for consistent hashing, must be prime number limited to 5000011."', args=[d.arg(name='tableSize', type=d.T.integer)]),
            withTableSize(tableSize): { backendSettings+: { loadBalancer+: { consistentHash+: { tableSize: tableSize } } } },
            '#withType':: d.fn(help='"ConsistentHashType defines the type of input to hash on. Valid Type values are\\n\\"SourceIP\\",\\n\\"Header\\",\\n\\"Cookie\\"."', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { backendSettings+: { loadBalancer+: { consistentHash+: { type: type } } } },
          },
          '#slowStart':: d.obj(help='"SlowStart defines the configuration related to the slow start load balancer policy.\\nIf set, during slow start window, traffic sent to the newly added hosts will gradually increase.\\nCurrently this is only supported for RoundRobin and LeastRequest load balancers"'),
          slowStart: {
            '#withWindow':: d.fn(help='"Window defines the duration of the warm up period for newly added host.\\nDuring slow start window, traffic sent to the newly added hosts will gradually increase.\\nCurrently only supports linear growth of traffic. For additional details,\\nsee https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-slowstartconfig"', args=[d.arg(name='window', type=d.T.string)]),
            withWindow(window): { backendSettings+: { loadBalancer+: { slowStart+: { window: window } } } },
          },
          '#withType':: d.fn(help='"Type decides the type of Load Balancer policy.\\nValid LoadBalancerType values are\\n\\"ConsistentHash\\",\\n\\"LeastRequest\\",\\n\\"Random\\",\\n\\"RoundRobin\\"."', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { backendSettings+: { loadBalancer+: { type: type } } },
        },
        '#proxyProtocol':: d.obj(help='"ProxyProtocol enables the Proxy Protocol when communicating with the backend."'),
        proxyProtocol: {
          '#withVersion':: d.fn(help='"Version of ProxyProtol\\nValid ProxyProtocolVersion values are\\n\\"V1\\"\\n\\"V2\\', args=[d.arg(name='version', type=d.T.string)]),
          withVersion(version): { backendSettings+: { proxyProtocol+: { version: version } } },
        },
        '#retry':: d.obj(help='"Retry provides more advanced usage, allowing users to customize the number of retries, retry fallback strategy, and retry triggering conditions.\\nIf not set, retry will be disabled."'),
        retry: {
          '#perRetry':: d.obj(help='"PerRetry is the retry policy to be applied per retry attempt."'),
          perRetry: {
            '#backOff':: d.obj(help='"Backoff is the backoff policy to be applied per retry attempt. gateway uses a fully jittered exponential\\nback-off algorithm for retries. For additional details,\\nsee https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-max-retries"'),
            backOff: {
              '#withBaseInterval':: d.fn(help='"BaseInterval is the base interval between retries."', args=[d.arg(name='baseInterval', type=d.T.string)]),
              withBaseInterval(baseInterval): { backendSettings+: { retry+: { perRetry+: { backOff+: { baseInterval: baseInterval } } } } },
              '#withMaxInterval':: d.fn(help='"MaxInterval is the maximum interval between retries. This parameter is optional, but must be greater than or equal to the base_interval if set.\\nThe default is 10 times the base_interval"', args=[d.arg(name='maxInterval', type=d.T.string)]),
              withMaxInterval(maxInterval): { backendSettings+: { retry+: { perRetry+: { backOff+: { maxInterval: maxInterval } } } } },
            },
            '#withTimeout':: d.fn(help='"Timeout is the timeout per retry attempt."', args=[d.arg(name='timeout', type=d.T.string)]),
            withTimeout(timeout): { backendSettings+: { retry+: { perRetry+: { timeout: timeout } } } },
          },
          '#retryOn':: d.obj(help='"RetryOn specifies the retry trigger condition.\\n\\nIf not specified, the default is to retry on connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes(503)."'),
          retryOn: {
            '#withHttpStatusCodes':: d.fn(help='"HttpStatusCodes specifies the http status codes to be retried.\\nThe retriable-status-codes trigger must also be configured for these status codes to trigger a retry."', args=[d.arg(name='httpStatusCodes', type=d.T.array)]),
            withHttpStatusCodes(httpStatusCodes): { backendSettings+: { retry+: { retryOn+: { httpStatusCodes: if std.isArray(v=httpStatusCodes) then httpStatusCodes else [httpStatusCodes] } } } },
            '#withHttpStatusCodesMixin':: d.fn(help='"HttpStatusCodes specifies the http status codes to be retried.\\nThe retriable-status-codes trigger must also be configured for these status codes to trigger a retry."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='httpStatusCodes', type=d.T.array)]),
            withHttpStatusCodesMixin(httpStatusCodes): { backendSettings+: { retry+: { retryOn+: { httpStatusCodes+: if std.isArray(v=httpStatusCodes) then httpStatusCodes else [httpStatusCodes] } } } },
            '#withTriggers':: d.fn(help='"Triggers specifies the retry trigger condition(Http/Grpc)."', args=[d.arg(name='triggers', type=d.T.array)]),
            withTriggers(triggers): { backendSettings+: { retry+: { retryOn+: { triggers: if std.isArray(v=triggers) then triggers else [triggers] } } } },
            '#withTriggersMixin':: d.fn(help='"Triggers specifies the retry trigger condition(Http/Grpc)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='triggers', type=d.T.array)]),
            withTriggersMixin(triggers): { backendSettings+: { retry+: { retryOn+: { triggers+: if std.isArray(v=triggers) then triggers else [triggers] } } } },
          },
          '#withNumRetries':: d.fn(help='"NumRetries is the number of retries to be attempted. Defaults to 2."', args=[d.arg(name='numRetries', type=d.T.integer)]),
          withNumRetries(numRetries): { backendSettings+: { retry+: { numRetries: numRetries } } },
        },
        '#tcpKeepalive':: d.obj(help='"TcpKeepalive settings associated with the upstream client connection.\\nDisabled by default."'),
        tcpKeepalive: {
          '#withIdleTime':: d.fn(help='"The duration a connection needs to be idle before keep-alive\\nprobes start being sent.\\nThe duration format is\\nDefaults to `7200s`."', args=[d.arg(name='idleTime', type=d.T.string)]),
          withIdleTime(idleTime): { backendSettings+: { tcpKeepalive+: { idleTime: idleTime } } },
          '#withInterval':: d.fn(help='"The duration between keep-alive probes.\\nDefaults to `75s`."', args=[d.arg(name='interval', type=d.T.string)]),
          withInterval(interval): { backendSettings+: { tcpKeepalive+: { interval: interval } } },
          '#withProbes':: d.fn(help='"The total number of unacknowledged probes to send before deciding\\nthe connection is dead.\\nDefaults to 9."', args=[d.arg(name='probes', type=d.T.integer)]),
          withProbes(probes): { backendSettings+: { tcpKeepalive+: { probes: probes } } },
        },
        '#timeout':: d.obj(help='"Timeout settings for the backend connections."'),
        timeout: {
          '#http':: d.obj(help='"Timeout settings for HTTP."'),
          http: {
            '#withConnectionIdleTimeout':: d.fn(help='"The idle timeout for an HTTP connection. Idle time is defined as a period in which there are no active requests in the connection.\\nDefault: 1 hour."', args=[d.arg(name='connectionIdleTimeout', type=d.T.string)]),
            withConnectionIdleTimeout(connectionIdleTimeout): { backendSettings+: { timeout+: { http+: { connectionIdleTimeout: connectionIdleTimeout } } } },
            '#withMaxConnectionDuration':: d.fn(help='"The maximum duration of an HTTP connection.\\nDefault: unlimited."', args=[d.arg(name='maxConnectionDuration', type=d.T.string)]),
            withMaxConnectionDuration(maxConnectionDuration): { backendSettings+: { timeout+: { http+: { maxConnectionDuration: maxConnectionDuration } } } },
            '#withRequestTimeout':: d.fn(help='"RequestTimeout is the time until which entire response is received from the upstream."', args=[d.arg(name='requestTimeout', type=d.T.string)]),
            withRequestTimeout(requestTimeout): { backendSettings+: { timeout+: { http+: { requestTimeout: requestTimeout } } } },
          },
          '#tcp':: d.obj(help='"Timeout settings for TCP."'),
          tcp: {
            '#withConnectTimeout':: d.fn(help='"The timeout for network connection establishment, including TCP and TLS handshakes.\\nDefault: 10 seconds."', args=[d.arg(name='connectTimeout', type=d.T.string)]),
            withConnectTimeout(connectTimeout): { backendSettings+: { timeout+: { tcp+: { connectTimeout: connectTimeout } } } },
          },
        },
      },
      '#metadata':: d.obj(help='"Metadata defines options related to the sending and receiving of dynamic metadata.\\nThese options define which metadata namespaces would be sent to the processor and which dynamic metadata\\nnamespaces the processor would be permitted to emit metadata to.\\nUsers can specify custom namespaces or well-known envoy metadata namespace (such as envoy.filters.http.ext_authz)\\ndocumented here: https://www.envoyproxy.io/docs/envoy/latest/configuration/advanced/well_known_dynamic_metadata#well-known-dynamic-metadata\\nDefault: no metadata context is sent or received from the external processor"'),
      metadata: {
        '#withAccessibleNamespaces':: d.fn(help='"AccessibleNamespaces are metadata namespaces that are sent to the external processor as context"', args=[d.arg(name='accessibleNamespaces', type=d.T.array)]),
        withAccessibleNamespaces(accessibleNamespaces): { metadata+: { accessibleNamespaces: if std.isArray(v=accessibleNamespaces) then accessibleNamespaces else [accessibleNamespaces] } },
        '#withAccessibleNamespacesMixin':: d.fn(help='"AccessibleNamespaces are metadata namespaces that are sent to the external processor as context"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='accessibleNamespaces', type=d.T.array)]),
        withAccessibleNamespacesMixin(accessibleNamespaces): { metadata+: { accessibleNamespaces+: if std.isArray(v=accessibleNamespaces) then accessibleNamespaces else [accessibleNamespaces] } },
        '#withWritableNamespaces':: d.fn(help='"WritableNamespaces are metadata namespaces that the external processor can write to"', args=[d.arg(name='writableNamespaces', type=d.T.array)]),
        withWritableNamespaces(writableNamespaces): { metadata+: { writableNamespaces: if std.isArray(v=writableNamespaces) then writableNamespaces else [writableNamespaces] } },
        '#withWritableNamespacesMixin':: d.fn(help='"WritableNamespaces are metadata namespaces that the external processor can write to"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='writableNamespaces', type=d.T.array)]),
        withWritableNamespacesMixin(writableNamespaces): { metadata+: { writableNamespaces+: if std.isArray(v=writableNamespaces) then writableNamespaces else [writableNamespaces] } },
      },
      '#processingMode':: d.obj(help='"ProcessingMode defines how request and response body is processed\\nDefault: header and body are not sent to the external processor"'),
      processingMode: {
        '#request':: d.obj(help='"Defines processing mode for requests. If present, request headers are sent. Request body is processed according\\nto the specified mode."'),
        request: {
          '#withAttributes':: d.fn(help='"Defines which attributes are sent to the external processor. Envoy Gateway currently\\nsupports only the following attribute prefixes: connection, source, destination,\\nrequest, response, upstream and xds.route.\\nhttps://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes"', args=[d.arg(name='attributes', type=d.T.array)]),
          withAttributes(attributes): { processingMode+: { request+: { attributes: if std.isArray(v=attributes) then attributes else [attributes] } } },
          '#withAttributesMixin':: d.fn(help='"Defines which attributes are sent to the external processor. Envoy Gateway currently\\nsupports only the following attribute prefixes: connection, source, destination,\\nrequest, response, upstream and xds.route.\\nhttps://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='attributes', type=d.T.array)]),
          withAttributesMixin(attributes): { processingMode+: { request+: { attributes+: if std.isArray(v=attributes) then attributes else [attributes] } } },
          '#withBody':: d.fn(help='"Defines body processing mode"', args=[d.arg(name='body', type=d.T.string)]),
          withBody(body): { processingMode+: { request+: { body: body } } },
        },
        '#response':: d.obj(help='"Defines processing mode for responses. If present, response headers are sent. Response body is processed according\\nto the specified mode."'),
        response: {
          '#withAttributes':: d.fn(help='"Defines which attributes are sent to the external processor. Envoy Gateway currently\\nsupports only the following attribute prefixes: connection, source, destination,\\nrequest, response, upstream and xds.route.\\nhttps://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes"', args=[d.arg(name='attributes', type=d.T.array)]),
          withAttributes(attributes): { processingMode+: { response+: { attributes: if std.isArray(v=attributes) then attributes else [attributes] } } },
          '#withAttributesMixin':: d.fn(help='"Defines which attributes are sent to the external processor. Envoy Gateway currently\\nsupports only the following attribute prefixes: connection, source, destination,\\nrequest, response, upstream and xds.route.\\nhttps://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='attributes', type=d.T.array)]),
          withAttributesMixin(attributes): { processingMode+: { response+: { attributes+: if std.isArray(v=attributes) then attributes else [attributes] } } },
          '#withBody':: d.fn(help='"Defines body processing mode"', args=[d.arg(name='body', type=d.T.string)]),
          withBody(body): { processingMode+: { response+: { body: body } } },
        },
        '#withAllowModeOverride':: d.fn(help='"AllowModeOverride allows the external processor to override the processing mode set via the\\n`mode_override` field in the gRPC response message. This defaults to false."', args=[d.arg(name='allowModeOverride', type=d.T.boolean)]),
        withAllowModeOverride(allowModeOverride): { processingMode+: { allowModeOverride: allowModeOverride } },
      },
      '#withBackendRefs':: d.fn(help='"BackendRefs references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent."', args=[d.arg(name='backendRefs', type=d.T.array)]),
      withBackendRefs(backendRefs): { backendRefs: if std.isArray(v=backendRefs) then backendRefs else [backendRefs] },
      '#withBackendRefsMixin':: d.fn(help='"BackendRefs references a Kubernetes object that represents the\\nbackend server to which the authorization request will be sent."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='backendRefs', type=d.T.array)]),
      withBackendRefsMixin(backendRefs): { backendRefs+: if std.isArray(v=backendRefs) then backendRefs else [backendRefs] },
      '#withFailOpen':: d.fn(help='"FailOpen defines if requests or responses that cannot be processed due to connectivity to the\\nexternal processor are terminated or passed-through.\\nDefault: false"', args=[d.arg(name='failOpen', type=d.T.boolean)]),
      withFailOpen(failOpen): { failOpen: failOpen },
      '#withMessageTimeout':: d.fn(help='"MessageTimeout is the timeout for a response to be returned from the external processor\\nDefault: 200ms"', args=[d.arg(name='messageTimeout', type=d.T.string)]),
      withMessageTimeout(messageTimeout): { messageTimeout: messageTimeout },
    },
    '#lua':: d.obj(help='"Lua is an ordered list of Lua filters\\nthat should be added to the envoy filter chain"'),
    lua: {
      '#valueRef':: d.obj(help='"ValueRef has the source code specified as a local object reference.\\nOnly a reference to ConfigMap is supported.\\nThe value of key `lua` in the ConfigMap will be used.\\nIf the key is not found, the first value in the ConfigMap will be used."'),
      valueRef: {
        '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
        withGroup(group): { valueRef+: { group: group } },
        '#withKind':: d.fn(help='"Kind is kind of the referent. For example \\"HTTPRoute\\" or \\"Service\\"."', args=[d.arg(name='kind', type=d.T.string)]),
        withKind(kind): { valueRef+: { kind: kind } },
        '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { valueRef+: { name: name } },
      },
      '#withInline':: d.fn(help='"Inline contains the source code as an inline string."', args=[d.arg(name='inline', type=d.T.string)]),
      withInline(inline): { inline: inline },
      '#withType':: d.fn(help='"Type is the type of method to use to read the Lua value.\\nValid values are Inline and ValueRef, default is Inline."', args=[d.arg(name='type', type=d.T.string)]),
      withType(type): { type: type },
    },
    '#targetRef':: d.obj(help='"TargetRef is the name of the resource this policy is being attached to.\\nThis policy and the TargetRef MUST be in the same namespace for this\\nPolicy to have effect\\n\\nDeprecated: use targetRefs/targetSelectors instead"'),
    targetRef: {
      '#withGroup':: d.fn(help='"Group is the group of the target resource."', args=[d.arg(name='group', type=d.T.string)]),
      withGroup(group): { spec+: { targetRef+: { group: group } } },
      '#withKind':: d.fn(help='"Kind is kind of the target resource."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { targetRef+: { kind: kind } } },
      '#withName':: d.fn(help='"Name is the name of the target resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { targetRef+: { name: name } } },
      '#withSectionName':: d.fn(help="\"SectionName is the name of a section within the target resource. When\\nunspecified, this targetRef targets the entire resource. In the following\\nresources, SectionName is interpreted as the following:\\n\\n* Gateway: Listener name\\n* HTTPRoute: HTTPRouteRule name\\n* Service: Port name\\n\\nIf a SectionName is specified, but does not exist on the targeted object,\\nthe Policy must fail to attach, and the policy implementation should record\\na `ResolvedRefs` or similar Condition in the Policy's status.\"", args=[d.arg(name='sectionName', type=d.T.string)]),
      withSectionName(sectionName): { spec+: { targetRef+: { sectionName: sectionName } } },
    },
    '#targetRefs':: d.obj(help='"TargetRefs are the names of the Gateway resources this policy\\nis being attached to."'),
    targetRefs: {
      '#withGroup':: d.fn(help='"Group is the group of the target resource."', args=[d.arg(name='group', type=d.T.string)]),
      withGroup(group): { group: group },
      '#withKind':: d.fn(help='"Kind is kind of the target resource."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { kind: kind },
      '#withName':: d.fn(help='"Name is the name of the target resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withSectionName':: d.fn(help="\"SectionName is the name of a section within the target resource. When\\nunspecified, this targetRef targets the entire resource. In the following\\nresources, SectionName is interpreted as the following:\\n\\n* Gateway: Listener name\\n* HTTPRoute: HTTPRouteRule name\\n* Service: Port name\\n\\nIf a SectionName is specified, but does not exist on the targeted object,\\nthe Policy must fail to attach, and the policy implementation should record\\na `ResolvedRefs` or similar Condition in the Policy's status.\"", args=[d.arg(name='sectionName', type=d.T.string)]),
      withSectionName(sectionName): { sectionName: sectionName },
    },
    '#targetSelectors':: d.obj(help='"TargetSelectors allow targeting resources for this policy based on labels"'),
    targetSelectors: {
      '#withGroup':: d.fn(help='"Group is the group that this selector targets. Defaults to gateway.networking.k8s.io"', args=[d.arg(name='group', type=d.T.string)]),
      withGroup(group): { group: group },
      '#withKind':: d.fn(help='"Kind is the resource kind that this selector targets."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { kind: kind },
      '#withMatchLabels':: d.fn(help='"MatchLabels are the set of label selectors for identifying the targeted resource"', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { matchLabels: matchLabels },
      '#withMatchLabelsMixin':: d.fn(help='"MatchLabels are the set of label selectors for identifying the targeted resource"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { matchLabels+: matchLabels },
    },
    '#wasm':: d.obj(help='"Wasm is a list of Wasm extensions to be loaded by the Gateway.\\nOrder matters, as the extensions will be loaded in the order they are\\ndefined in this list."'),
    wasm: {
      '#code':: d.obj(help='"Code is the Wasm code for the extension."'),
      code: {
        '#http':: d.obj(help='"HTTP is the HTTP URL containing the Wasm code.\\n\\nNote that the HTTP server must be accessible from the Envoy proxy."'),
        http: {
          '#withSha256':: d.fn(help='"SHA256 checksum that will be used to verify the Wasm code.\\n\\nIf not specified, Envoy Gateway will not verify the downloaded Wasm code.\\nkubebuilder:validation:Pattern=`^[a-f0-9]{64}$`"', args=[d.arg(name='sha256', type=d.T.string)]),
          withSha256(sha256): { code+: { http+: { sha256: sha256 } } },
          '#withUrl':: d.fn(help='"URL is the URL containing the Wasm code."', args=[d.arg(name='url', type=d.T.string)]),
          withUrl(url): { code+: { http+: { url: url } } },
        },
        '#image':: d.obj(help='"Image is the OCI image containing the Wasm code.\\n\\nNote that the image must be accessible from the Envoy Gateway."'),
        image: {
          '#pullSecretRef':: d.obj(help='"PullSecretRef is a reference to the secret containing the credentials to pull the image.\\nOnly support Kubernetes Secret resource from the same namespace."'),
          pullSecretRef: {
            '#withGroup':: d.fn(help='"Group is the group of the referent. For example, \\"gateway.networking.k8s.io\\".\\nWhen unspecified or empty string, core API group is inferred."', args=[d.arg(name='group', type=d.T.string)]),
            withGroup(group): { code+: { image+: { pullSecretRef+: { group: group } } } },
            '#withKind':: d.fn(help='"Kind is kind of the referent. For example \\"Secret\\"."', args=[d.arg(name='kind', type=d.T.string)]),
            withKind(kind): { code+: { image+: { pullSecretRef+: { kind: kind } } } },
            '#withName':: d.fn(help='"Name is the name of the referent."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { code+: { image+: { pullSecretRef+: { name: name } } } },
            '#withNamespace':: d.fn(help="\"Namespace is the namespace of the referenced object. When unspecified, the local\\nnamespace is inferred.\\n\\nNote that when a namespace different than the local namespace is specified,\\na ReferenceGrant object is required in the referent namespace to allow that\\nnamespace's owner to accept the reference. See the ReferenceGrant\\ndocumentation for details.\\n\\nSupport: Core\"", args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { code+: { image+: { pullSecretRef+: { namespace: namespace } } } },
          },
          '#withSha256':: d.fn(help='"SHA256 checksum that will be used to verify the OCI image.\\n\\nIt must match the digest of the OCI image.\\n\\nIf not specified, Envoy Gateway will not verify the downloaded OCI image.\\nkubebuilder:validation:Pattern=`^[a-f0-9]{64}$`"', args=[d.arg(name='sha256', type=d.T.string)]),
          withSha256(sha256): { code+: { image+: { sha256: sha256 } } },
          '#withUrl':: d.fn(help='"URL is the URL of the OCI image.\\nURL can be in the format of `registry/image:tag` or `registry/image@sha256:digest`."', args=[d.arg(name='url', type=d.T.string)]),
          withUrl(url): { code+: { image+: { url: url } } },
        },
        '#withPullPolicy':: d.fn(help='"PullPolicy is the policy to use when pulling the Wasm module by either the HTTP or Image source.\\nThis field is only applicable when the SHA256 field is not set.\\n\\nIf not specified, the default policy is IfNotPresent except for OCI images whose tag is latest.\\n\\nNote: EG does not update the Wasm module every time an Envoy proxy requests\\nthe Wasm module even if the pull policy is set to Always.\\nIt only updates the Wasm module when the EnvoyExtension resource version changes."', args=[d.arg(name='pullPolicy', type=d.T.string)]),
        withPullPolicy(pullPolicy): { code+: { pullPolicy: pullPolicy } },
        '#withType':: d.fn(help='"Type is the type of the source of the Wasm code.\\nValid WasmCodeSourceType values are \\"HTTP\\" or \\"Image\\"."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { code+: { type: type } },
      },
      '#env':: d.obj(help='"Env configures the environment for the Wasm extension"'),
      env: {
        '#withHostKeys':: d.fn(help='"HostKeys is a list of keys for environment variables from the host envoy process\\nthat should be passed into the Wasm VM. This is useful for passing secrets to to Wasm extensions."', args=[d.arg(name='hostKeys', type=d.T.array)]),
        withHostKeys(hostKeys): { env+: { hostKeys: if std.isArray(v=hostKeys) then hostKeys else [hostKeys] } },
        '#withHostKeysMixin':: d.fn(help='"HostKeys is a list of keys for environment variables from the host envoy process\\nthat should be passed into the Wasm VM. This is useful for passing secrets to to Wasm extensions."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='hostKeys', type=d.T.array)]),
        withHostKeysMixin(hostKeys): { env+: { hostKeys+: if std.isArray(v=hostKeys) then hostKeys else [hostKeys] } },
      },
      '#withConfig':: d.fn(help='"Config is the configuration for the Wasm extension.\\nThis configuration will be passed as a JSON string to the Wasm extension."', args=[d.arg(name='config', type=d.T.any)]),
      withConfig(config): { config: config },
      '#withFailOpen':: d.fn(help='"FailOpen is a switch used to control the behavior when a fatal error occurs\\nduring the initialization or the execution of the Wasm extension.\\nIf FailOpen is set to true, the system bypasses the Wasm extension and\\nallows the traffic to pass through. Otherwise, if it is set to false or\\nnot set (defaulting to false), the system blocks the traffic and returns\\nan HTTP 5xx error."', args=[d.arg(name='failOpen', type=d.T.boolean)]),
      withFailOpen(failOpen): { failOpen: failOpen },
      '#withName':: d.fn(help="\"Name is a unique name for this Wasm extension. It is used to identify the\\nWasm extension if multiple extensions are handled by the same vm_id and root_id.\\nIt's also used for logging/debugging.\\nIf not specified, EG will generate a unique name for the Wasm extension.\"", args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withRootID':: d.fn(help='"RootID is a unique ID for a set of extensions in a VM which will share a\\nRootContext and Contexts if applicable (e.g., an Wasm HttpFilter and an Wasm AccessLog).\\nIf left blank, all extensions with a blank root_id with the same vm_id will share Context(s).\\n\\nNote: RootID must match the root_id parameter used to register the Context in the Wasm code."', args=[d.arg(name='rootID', type=d.T.string)]),
      withRootID(rootID): { rootID: rootID },
    },
    '#withExtProc':: d.fn(help='"ExtProc is an ordered list of external processing filters\\nthat should be added to the envoy filter chain"', args=[d.arg(name='extProc', type=d.T.array)]),
    withExtProc(extProc): { spec+: { extProc: if std.isArray(v=extProc) then extProc else [extProc] } },
    '#withExtProcMixin':: d.fn(help='"ExtProc is an ordered list of external processing filters\\nthat should be added to the envoy filter chain"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='extProc', type=d.T.array)]),
    withExtProcMixin(extProc): { spec+: { extProc+: if std.isArray(v=extProc) then extProc else [extProc] } },
    '#withLua':: d.fn(help='"Lua is an ordered list of Lua filters\\nthat should be added to the envoy filter chain"', args=[d.arg(name='lua', type=d.T.array)]),
    withLua(lua): { spec+: { lua: if std.isArray(v=lua) then lua else [lua] } },
    '#withLuaMixin':: d.fn(help='"Lua is an ordered list of Lua filters\\nthat should be added to the envoy filter chain"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='lua', type=d.T.array)]),
    withLuaMixin(lua): { spec+: { lua+: if std.isArray(v=lua) then lua else [lua] } },
    '#withTargetRefs':: d.fn(help='"TargetRefs are the names of the Gateway resources this policy\\nis being attached to."', args=[d.arg(name='targetRefs', type=d.T.array)]),
    withTargetRefs(targetRefs): { spec+: { targetRefs: if std.isArray(v=targetRefs) then targetRefs else [targetRefs] } },
    '#withTargetRefsMixin':: d.fn(help='"TargetRefs are the names of the Gateway resources this policy\\nis being attached to."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetRefs', type=d.T.array)]),
    withTargetRefsMixin(targetRefs): { spec+: { targetRefs+: if std.isArray(v=targetRefs) then targetRefs else [targetRefs] } },
    '#withTargetSelectors':: d.fn(help='"TargetSelectors allow targeting resources for this policy based on labels"', args=[d.arg(name='targetSelectors', type=d.T.array)]),
    withTargetSelectors(targetSelectors): { spec+: { targetSelectors: if std.isArray(v=targetSelectors) then targetSelectors else [targetSelectors] } },
    '#withTargetSelectorsMixin':: d.fn(help='"TargetSelectors allow targeting resources for this policy based on labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetSelectors', type=d.T.array)]),
    withTargetSelectorsMixin(targetSelectors): { spec+: { targetSelectors+: if std.isArray(v=targetSelectors) then targetSelectors else [targetSelectors] } },
    '#withWasm':: d.fn(help='"Wasm is a list of Wasm extensions to be loaded by the Gateway.\\nOrder matters, as the extensions will be loaded in the order they are\\ndefined in this list."', args=[d.arg(name='wasm', type=d.T.array)]),
    withWasm(wasm): { spec+: { wasm: if std.isArray(v=wasm) then wasm else [wasm] } },
    '#withWasmMixin':: d.fn(help='"Wasm is a list of Wasm extensions to be loaded by the Gateway.\\nOrder matters, as the extensions will be loaded in the order they are\\ndefined in this list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='wasm', type=d.T.array)]),
    withWasmMixin(wasm): { spec+: { wasm+: if std.isArray(v=wasm) then wasm else [wasm] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
